### PR TITLE
Replaced bootstrap-tour with introJs tour library in Write Activity

### PR DESCRIPTION
**Pull request by Ayeshashaik759**
I have migrated Write activity tutorial from bootstrap-tour to IntroJs
Issue: https://github.com/llaske/sugarizer/issues/1090

### CODE REVIEW

**Comment by llaske** [comment]
There is an issue: the tutorial popup is displayed for icons not visible (due to window size) in the toolbar.

image

**Comment by Ayeshashaik759** [comment]
@llaske  Can you any suggestions to solve this issue

**Comment by llaske** [comment]
The filter part in tutorial method should handle this: filter step pointing on hidden element.
Check if it works.

**Comment by Ayeshashaik759** [comment]
The order of icons visible in your toolbar is different from order I am getting and I got the order of icons same as in the sugarizer.org website so I am little bit confused as I can't figure out the issue clearly. But I will take time and try to analyse and solve the issue.

**Pull request closed without merging**
