### PR TITLE
Replaced Bootstrap tour by IntroJs in EBook Activity

### PR DESCRIPTION
**Pull request by ABHINAV-JHA-27**
Migrated EBook Activity from Bootstrap Tour to IntroJs https://github.com/llaske/sugarizer/issues/1090

### CODE REVIEW

**Comment by ABHINAV-JHA-27** [comment]
Hey @llaske , I have Migrated the EBook Activity's Tutorial to IntroJS. Can you please Review it.

**Comment by llaske** [comment]
Do not change indentation style in files. Only updated lines should be changed in files.
Check your IDE options.

**Comment by ABHINAV-JHA-27** [comment]
Hey @llaske , sorry for the formatting issue will definately remember it from next time. can you review

**Comment by llaske** [comment]
No, sorry @ABHINAV-JHA-27 you need to update your PR to reset indentation.
For maintenance reason, it's very important to be able to see which PR impact which lines.

**Pull request closed without merging**
