### PR TITLE
created webL10n.js for clock

### PR DESCRIPTION
**Pull request by samswag**
Starting a my  GCI project with clock activity

### CODE REVIEW

**Comment by llaske** [comment]
The webL10n.js is already in the lib directory.

**Comment by samswag** [comment]
the problem is that, i can't figure out what strings i can translate.
Because the activity itself don't display much of text

**Comment by llaske** [comment]
The idea is to translate the time string:

clock

I suggest using the moment.js library, already used in the Moon activity.

**Comment by samswag** [comment]
oh! let me look at it

**Pull request closed without merging**
