### PR TITLE
Addded confirm message for deletion in Exerciser activity

### PR DESCRIPTION
**Pull request by Scar26**
Added a confirmation message for dialogue deletion in Exerciser activity as requested in #285 .
Hopefully this fixes the issue.

### CODE REVIEW

**Comment by Scar26** [comment]
@llaske I was thinking of styling the confirm button to match the rest of the UI instead of using the default in electron. Is it fine if I use Jquery UI or should I stick to vanilla javascript?

**Comment by llaske** [comment]
Exerciser activity is written using ReactJS. Only the build code is integrated in Sugarizer.
So for this activity, don't do a PR here, do it on https://github.com/llaske/ExerciserReact

**Comment by Scar26** [comment]
@llaske Done

**Comment by llaske** [comment]
Related to https://github.com/llaske/ExerciserReact/pull/11

**Pull request closed without merging**
