### PR TITLE
Replaced bootstrap-tour with introJs tour library in Tangram activity

### PR DESCRIPTION
**Pull request by abhishek-sultaniya**
Fixes: #1090 
Replaced bootstrap-tour with introJs library in Tangram Activity.

### CODE REVIEW

**Comment by llaske** [comment]
There is lot of change in `activity.js` not related with the issue (quote replacement, coma added, ...).
You should disable automatic change in your IDE to keep only changes need for the PR.

**Comment by abhishek-sultaniya** [comment]
OK,will take care of this from next time.
In recent commit I have corrected it.

**Comment by llaske** [comment]
I don't see any change :thinking:

**Comment by abhishek-sultaniya** [comment]
I have made changes in activity.js file.Should I change indentation in any other file?

**Comment by llaske** [comment]
@abhishek-sultaniya I mean this change:

image

**Comment by abhishek-sultaniya** [comment]
Yes,I have corrected this in last commit.
image
Now its showing only 8 files have been changed and it does not include activity.js

**Comment by llaske** [comment]
@abhishek-sultaniya you're right it's fixed in `activity.js`.
Could you also fix indentation style in `SugarTutorial.js`? Was TAB and you replaced it by SPACES.

**Comment by llaske** [comment]
Close due to lack of activity. @abhishek-sultaniya feel free to reopen it if need.

**Pull request closed without merging**
