### PR TITLE
Story activity : Mouse cursor UI enhancement

### PR DESCRIPTION
**Pull request by Ydvaaman**
## Hey @llaske 
I have fixed the mouse cursor UI issue in the Story activity, please review it.
Refer issue:https://github.com/llaske/sugarizer/issues/1254

# Before

# After
WhatsApp Image 2023-03-06 at 1 04 35 AM

### CODE REVIEW

**Comment by llaske** [comment]
I'm not in favor to patch external library.
If there's no other way, let's ignore the issue.

**Comment by Ydvaaman** [comment]
ok, @llaske I will find another way and try to fix it 👍

**Comment by Ydvaaman** [comment]
## Hi @llaske, 
I was able to resolve the issue that was reported in the Github issue https://github.com/llaske/sugarizer/issues/1254 by following your suggestion to implement a simple fix.

 I completed the following steps in order to resolve the issue:

* Navigated to the path /activities/<Story Activity>/lib/sugar-web/graphics/css/ in the project directory.
* Opened the file sugar-96dpi.css using a code editor.
* Located the body element within the CSS file.
* Added the CSS property cursor: default to the body element.
I have tested the fix and confirmed that the UI issue has been resolved.

**Comment by llaske** [comment]
Thanks but it's superseded by https://github.com/llaske/sugarizer/pull/1296

**Comment by Ydvaaman** [comment]
Hey @llaske 
I want to clarify that although PR https://github.com/llaske/sugarizer/pull/1296 fixes the cursor issue for text area elements in all activities of the project, it doesn't address the issue I raised in this PR, which pertains cursor issue to a div with an overflow property.

**Comment by llaske** [comment]
Anyway you should not update the Sugar-Web library who it shared with all other activities.

**Pull request closed without merging**
