### PR TITLE
Replaced webL10n to i18next in EbookReader_Activity

### PR DESCRIPTION
**Pull request by soham2312**
fix issue #1378 

Replaced Code in EbookReader Activity to i18next

@llaske , could you please review it

### CODE REVIEW

**Comment by llaske** [comment]
There is an error in the console and the tutorial doesn't work

image

**Comment by soham2312** [comment]
@llaske Sir,please review it

**Comment by llaske** [comment]
Nice. Thanks. 
Just: the `locale.ini` file is now useless, I've removed it.

**Comment by soham2312** [comment]
Thanks @llaske for removing it

**Pull request merged**
