### PR TITLE
Refactor code of presence popups in Memorize activity

### PR DESCRIPTION
**Pull request by sdziuda**
Currently I've replaced the code of presencepalette.js with the code from the same file from ActivityTemplate. I've also moved some of the deleted code into activity.js. I know that not everything is working fine. I will need some help with that because I have no clue what's working improperly. 

At this moment Join and Leave popups work fine. But the person who joins the host can't see the board.

### CODE REVIEW

**Comment by sdziuda** [comment]
I've made the code be very similiar to the one you can find in MazeWeb activity. Anyway the problem with person not seeing the board is still live and I really have no clue where it comes from.

**Comment by llaske** [comment]
I think you forget to call to `memorizeApp.onUsersListChanged` method.
It was called [here](https://github.com/llaske/sugarizer/pull/557/files#diff-a9819884ebd549090c650f4d206cc8b2L120) and it's not called anywhere in your new code.

**Comment by sdziuda** [comment]
I've added this method but it still doesn't change anything. Therefore I think that it's not the problem with `memorizeApp.onUsersListChanged` not being called. 
I think that the problem occurs because the player who joins doesn't get the message with the content, what is really weird because as you can see on the screenshot it is [sent](https://github.com/llaske/sugarizer/blob/84d8392ac29bdfaa3e4f2738835af7c8baf2f0aa/activities/Memorize.activity/js/activity.js#L130) but not[ delivered](https://github.com/llaske/sugarizer/blob/84d8392ac29bdfaa3e4f2738835af7c8baf2f0aa/activities/Memorize.activity/js/activity.js#L192).
image

**Comment by llaske** [comment]
Got it.
You send correctly the message but `sharedId` [here](https://github.com/llaske/sugarizer/pull/557/files#diff-a9819884ebd549090c650f4d206cc8b2R128) is `null` for the host. 
On the host, the `sharedId` is not received in the environment, it's build [here](https://github.com/llaske/sugarizer/pull/557/files#diff-a9819884ebd549090c650f4d206cc8b2R175) and you could get it by calling `presence.getSharedInfo().id`.

**Comment by sdziuda** [comment]
Thank you for noticing this!
Now the messages are sent and delivered properly. Nevertheless there is a problem with `lzstring.js` file. The error like on the screenshot occurs.

image

Maybe it's because of the [content](https://github.com/llaske/sugarizer/blob/4313515dcac987f1a9180b60f7598d2e5254734c/activities/Memorize.activity/js/activity.js#L127) of the message?

**Comment by llaske** [comment]
Look like you've sent [here](https://github.com/llaske/sugarizer/pull/557/files#diff-a9819884ebd549090c650f4d206cc8b2R130) a message non compressed.
You hate to compress the message using the `MemorizeApp.sendMessage` method [here](https://github.com/llaske/sugarizer/blob/4313515dcac987f1a9180b60f7598d2e5254734c/activities/Memorize.activity/js/memorize-app.js#L718).

**Comment by sdziuda** [comment]
You were right, after adding the compression sending the message works fine. Now the non-host players can see the board. So we've got a little success!
But the next problem is that the `displayUsersAndScores` function doesn't work. From what I've observed it's probably because of the `MemorizeApp.game.players.length` is returning 0 right [here](https://github.com/llaske/sugarizer/blob/f8715c83b43b26463e791a82160074272b6ab2fa/activities/Memorize.activity/js/memorize-app.js#L734). Because of the same reason the non-host player can't see which card has been clicked, I think that code responsible for this is [here](https://github.com/llaske/sugarizer/blob/f8715c83b43b26463e791a82160074272b6ab2fa/activities/Memorize.activity/js/memorize-app.js#L710).
I thought that maybe it's because of the `onUsersListChanged` function not working properly [here](https://github.com/llaske/sugarizer/blob/f8715c83b43b26463e791a82160074272b6ab2fa/activities/Memorize.activity/js/activity.js#L145) so I've tried moving it back to the `presencepalette.js` file and it didn't give any other output. Therefore I think it's not a problem.

**Comment by llaske** [comment]
I guess that most of problems come from the fact that you should yourself the `sendMessage` we mentioned earlier. 
Theoretically, you must not have to call it yourself. Everything (including handling players length) happens directly in the `MemorizeApp.onUsersListChanged` method.
Are you sure this method is still called?

**Comment by sdziuda** [comment]
Yes, it is called, but maybe because it's just a function in `activity.js` instead of being a prototype from `presencepalette.js` it isn't working properly. From what I've noticed the `memorizeApp.onUsersListChanged()` isn't even accessed [here](https://github.com/llaske/sugarizer/blob/f8715c83b43b26463e791a82160074272b6ab2fa/activities/Memorize.activity/js/activity.js#L146) while running the code online.

**Comment by llaske** [comment]
You're wrong, I've added a log message [here](https://github.com/llaske/sugarizer/blob/f8715c83b43b26463e791a82160074272b6ab2fa/activities/Memorize.activity/js/memorize-app.js#L819) and it's never called thought it was called in the initial source code.
I suggest you to remove your send call and try to understand how the message is never called.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/776

**Pull request closed without merging**
