### PR TITLE
Issue#594 Add tutorial to Chat Activity

### PR DESCRIPTION
**Pull request by Hemansh31**
@llaske I had to close my last PR #626 on the issue #594 due to some problem . I have done the changes you asked for in this new PR. Please review and suggest changes if required

### CODE REVIEW

**Comment by sarthak-g** [comment]
@Hemansh31 your branch is not updated.This PR also contains commit of another PR.

**Comment by Hemansh31** [comment]
@sarthak-g could you tell me how to update the branch for both my PRs?

**Comment by quozl** [comment]
Here's a visualisation of this pull request commit a1c9fff relative to the _dev_ branch;

tmp

You will see your branch diverged from dev a few days ago.

At the moment, it is easy to rebase;

```
git checkout dev
git pull
git checkout chat_Tutorial
git rebase dev
git push
```

For me using your branch the result looks like;

```
$ git rebase dev
First, rewinding head to replay your work on top of it...
Applying: Issue#594 Adding tutorial to Chat Activity
Applying: This is my submission of the ChessBoard Task for GSoC 2020. Also, Issue#592
Applying: Issue#594 Commit with changes requested upon review
```

tmp2

However, if you've never done rebase or merge conflict resolution before, I suggest taking a backup of your repository first.  If the _dev_ branch moves in a way that conflicts with what you are doing, you'd be forced into managing the conflict in your repository.  This is not enjoyable the first time. :grinning: 

For further information, look for documentation in GitHub on keeping a branch up to date or rebasing.  Don't be distracted by discussions about rebasing when merging a pull-request.  Similar sounding concept, but different.

**Comment by Hemansh31** [comment]
@quozl  I am getting that my branch is already up to date 
Screenshot from 2020-02-24 21-05-39

**Comment by Hemansh31** [comment]
@quozl What I understand is that I need to keep my branches updated with the remote dev branch and each issue can be commited in a new branch such that each branch has commits regarding that issue only? Is this what we want?

**Comment by s-mag** [comment]
@Hemansh31 Yes we have to do the same. For these PRs you can remove the latest commit by git reset or you can create new PR from a different branch...

**Comment by quozl** [comment]
Thanks for asking.

> @quozl I am getting that my branch is already up to date

This may happen if your origin remote is your own fork on GitHub.  You may benefit from adding the llaske/sugarizer repository as a remote and pull from it instead.

> @quozl What I understand is that I need to keep my branches updated with the remote dev branch and each issue can be commited in a new branch such that each branch has commits regarding that issue only? Is this what we want?

It helps.  Yours is an adequate explanation, but is also a simplification.

We have some maintainers as reviewers who find it more effective to solve any problem you've left them rather than demand you do it.  This saves on another communication round-trip.  It depends on the reviewer's time and the urgency of the work being done.

Our [Guide for Reviewers](https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#guide-for-reviewers) allows for "_not waste the time of the contributor, by doing anything trivial that otherwise the contributor might have to do._".  As a contributor you should also think like a reviewer, so that what you give them is as close as possible to what they want.

**Pull request closed without merging**
