### PR TITLE
Fixed Error

### PR DESCRIPTION
**Pull request by MananJain2002**
I have went through require.js documentations https://requirejs.org/ and have seen many articles about it Just by changing the loading time to fixes the bug

#1048

### CODE REVIEW

**Comment by llaske** [comment]
It doesn't fix the issue on my side.
Could you explain how it's suppose to fix the timeout problem?

**Comment by MananJain2002** [comment]
Hi @llaske sir, I referred this article https://www.moreonfew.com/load-timeout-for-modules-error-in-requirejs/ and then reequirejs documentations here https://requirejs.org/docs/api.html#config-map and https://requirejs.org/docs/errors.html even on stackoverflow page https://stackoverflow.com/questions/14279962/require-js-error-load-timeout-for-modules-backbone-jquerymobile after trying out different options it seams like by changing loading time of the page to zero solves it cause it render the page as fast as possible. I tried it on my local system as well it does solves in my system...

**Comment by llaske** [comment]
You're right it solve the issue.
BTW I'm skeptical about this fix:
- In Slow 3G condition it means that the user has to wait more than 2mn to see the activity screen. It will be unusable 
- I'm not in favor of changing code in standard libraries

**Comment by MananJain2002** [comment]
Hi @llaske sir actually I'm getting this error with 50mbps of internet speed as well as 80mbps I don't think it occurs only on slow 3g networks

https://user-images.githubusercontent.com/63538502/164953404-a168e40c-556d-4514-aea0-fea39d4a5ab3.mp4

by changing the code it actually fixes it...

**Comment by llaske** [comment]
> by changing the code it actually fixes it...

It doesn't fix the issue.
The issue is that it take too long time to load the page.
Waiting few minutes is not acceptable.
As I said, it's better in this case to use the offline version of Sugarizer.

**Pull request closed without merging**
