### PR TITLE
New Activity : VEDIC MATHS

### PR DESCRIPTION
**Pull request by abhishektanwar**
Vedic Maths is an activity that focuses on improving the mathematical calculation skills of users. It helps the user to learn various mathematical calculation tricks that can be employed by the user to do faster calculations in an interactive way.

### CODE REVIEW

**Comment by abhishektanwar** [comment]
@llaske please share your thoughts on this activity.

Working on: Full Screen functionality and responsiveness of activity.

**Comment by llaske** [comment]
The target for Sugar/Sugarizer is children between 6 and 12. It seems too complex for this target.
If you're interested by a Math activity, I suggest you to the Mind math activity proposal [here](https://github.com/sugarlabs/GSoC/blob/master/Ideas-2020.md#sugarizer-game-activity-pack).

**Comment by abhishektanwar** [comment]
@llaske we can reduce the level of difficulty of tricks that children can learn . If you like the concept of the activity

**Comment by llaske** [comment]
No I think it's too close to the Mind Math activity.

**Pull request closed without merging**
