### PR TITLE
Fix buttons text centre with icon #1052

### LINKED ISSUE #1052: some button text is not in centre with the icon
Screenshot from 2022-04-03 23-01-34
Screenshot from 2022-04-03 23-02-24

etc..!

### PR DESCRIPTION
**Pull request by codebloded**
FIXED #1052 

screenshots :arrow_down: 
Screenshot from 2022-04-04 16-17-23
Screenshot from 2022-04-04 16-17-01

@llaske have a look !

### CODE REVIEW

**Comment by codebloded** [comment]
Fixing clear search button under Journal in second commit 
screenshot :arrow_down: 
before :
Screenshot from 2022-04-04 17-00-38

after:
Screenshot from 2022-04-04 17-01-05

**Comment by AnandChourasia007** [comment]
Hi @codebloded , while you are at it, I think you can fix that alignment of the the icon with the text below it and the button. Seems the journal icon is slightly off to the right.

**Comment by codebloded** [comment]
yeeah  thanks @AnandChourasia007  i'll update the PR to set the button and all aligned centre

**Comment by S-kus** [comment]
Hey @codebloded, In starting at the login page also when we input the image there are two buttons `next` and `back`, they are also having this problem, which can be fixed.

**Comment by llaske** [comment]
You're right. Look better.

**Comment by llaske** [comment]
There is an issue. A scrolling bar now appears when creating an user.

Peek 07-04-2022 22-24

**Comment by S-kus** [comment]
> There is an issue. A scrolling bar now appears when creating an user.

@llaske This could be solved by adding `overflow-x: hidden;` in `#canvas` similar to `overflow-y: hidden`, In file `css/styles.css`.
As shown:
c

**Comment by codebloded** [comment]
> There is an issue. A scrolling bar now appears when creating an user.
> 
> Peek 07-04-2022 22-24

Okay @llaske   i'm doing these changes !  Thanks !

**Comment by codebloded** [comment]
@llaske  sir this is  DONE !!  have a look 

> There is an issue. A scrolling bar now appears when creating an user.
> 
> Peek 07-04-2022 22-24



screenshot :arrow_down: 

Screenshot from 2022-04-08 22-33-38

**Comment by codebloded** [comment]
> 

Hey @S-kus  I think is done ! by fixing `.icon-button-text` class  in `css/styles.css`  ! If there is any reply here ! 
and thanks a lot !

**Comment by llaske** [comment]
Nice. Thanks.

**Pull request merged**
