### PR TITLE
Add Unit Converter Activity

### PR DESCRIPTION
**Pull request by Anshuman71**
Add Unit converter activity to the activities
It will let users convert
1. Length
2. Weight
I am working to add more units soon (temprature, digital storage unit, speed etc)

Screenshot from 2019-03-16 11-36-15
Screenshot from 2019-03-16 11-35-49
Screenshot from 2019-03-16 11-35-57
Screenshot from 2019-03-16 11-36-04

_home_anshuman_Documents_gsoc_sugarizer_activities_UnitConverter activity_index html_aid=5d6a81ed-c4b3-433b-99e0-8b7db94635c4 a=org sugarlabs UnitConverter o=0bcf7f2c-82c1-4695-baf7-0b48f53f8612 n=UnitConverter%20Activity(iPhone 6_7_8 Plus)

The user interface is kept simple for the sake of accessibility.
Suggestions are welcomed.
Looking forward to adding more such activities soon.

### CODE REVIEW

**Comment by llaske** [comment]
Interesting but I'm not sure to see a pedagogical interest of this activity for children between 6 to 12.
They more learn about a specific unit without needing a conversion. 
On weight, an activity to learn how to determine a specific weight using a scaleboard - like in [GCompris Scaledboard activity](http://activities.sugarlabs.org/en/sugar/addon/4283) - could be more interesting.

**Comment by Anshuman71** [comment]
@llaske thank you for giving it a thought. I build this activity for students because as they grow up, they start to know about different units and get curious to know how they all are related to each other. Personally, when I was a kid I used to take my mother's phone to find conversions.
Moreover, some countries use imperial units while some use the metric system so it will be helpful for them to get familiar with them.
Please give this a thought.
I would love to hear your feedback

**Comment by llaske** [comment]
Conversions could be interesting in a pedagogic activity, it's why I pointed you the Scalesboard activity. But just a converter has no pedagogic value.

**Comment by Anshuman71** [comment]
@llaske I totally agree with you and I am now working on to make them more interesting and engaging.
I appreciate your help and suggestion

**Comment by Anshuman71** [comment]
I am closing this PR for now, I will update the activity with interactive and engaging stuff.

**Pull request closed without merging**
