### PR TITLE
Fix unexpected token in JSON Error

### PR DESCRIPTION
**Pull request by utkarsh-raj**
The original mentioned error was caused due to some non printable characters in the JSON String. These characters do not show but can break the parse function in the JSON Object in JS.

This was happening because the string was not cleaned before parsing. Applied standard cleaning techniques.

### CODE REVIEW

**Comment by llaske** [comment]
Please do not integrate two fixes in the same PR. This one contains #106 and #185. Thanks to split into two PR.

Regarding #185, your change seems to fix partially the issue. BTW CORS should be installed on the server, could you ask to Walter bender to add it?

**Comment by utkarsh-raj** [comment]
I am sorry. I will split the fix into two PR.

#185 is a partial fix, the issue now raised is probably an altogether different one. The console errors are regarding the server configuration, and the App must not hang on any device as there is no critical error.

I think that this fix solves the original problem for which the issue was opened, and the new issue can be opened for server configuration.

I will research a little and ask Walter Bender to review the suggestions.

**Comment by utkarsh-raj** [comment]
I have reverted the fix of the other issue from this branch. Please check @llaske .

**Comment by utkarsh-raj** [comment]
I am little unsure of the root cause. The App does not hang on any device because the JS error is fix. But the request URL does not look right to me. However, discussing this problem will deviate from the issue being raised in #185 . Should a new issue be open for @llaske ?

**Comment by llaske** [comment]
@utkarsh-raj yes it's a good idea to open a new issue on the CORS problem.

**Pull request merged**
