### PR TITLE
stopwatchActivity: Activity dropdown UI Fix

### PR DESCRIPTION
**Pull request by VedantSharma11**
## SNIPPETS
---
### After:
Screenshot 2023-03-07 193854

### CODE REVIEW

**Comment by llaske** [comment]
The `sugar-96dpi.css` file come from the Sugar-Web library and is share with all activities (see [here](https://github.com/llaske/sugarizer/blob/dev/docs/architecture.md)). It should not be updated in a single activity.

**Comment by VedantSharma11** [comment]
okay @llaske i'll try some other way to fix it

**Comment by llaske** [comment]
Nice. Thanks.

**Comment by VedantSharma11** [comment]
Thanks @llaske

**Pull request merged**
