### PR TITLE
Replaced WebL10n to i18next in Reflection Activity

### PR DESCRIPTION
**Pull request by vcvedika**
This PR fixes issue #1378 

@llaske could you please review the changes

### CODE REVIEW

**Comment by llaske** [comment]
The tutorial localization doesn't work :

image

**Comment by vcvedika** [comment]
@llaske I've resolved this issue, could you please review the changes

**Comment by llaske** [comment]
Nice job @vcvedika :+1: 

BTW the icons tooltip are not localized.

Capture d’écran du 2023-12-07 22-20-49

It's not related to your fix, it's just hard coded [here](https://github.com/llaske/sugarizer/blob/dev/activities/Reflection.activity/index.html#L27-L39).

Could you try to improve that?

I think you could use the `data-i18n` attribute and retrieve the code mentioned in the comment https://github.com/llaske/sugarizer-doc/issues/42

**Comment by vcvedika** [comment]
@llaske I plan to address the tooltip localization by creating a separate issue and working on it independently, as at present I am unable to figure out a working solution.

**Comment by Vishalk91-4** [comment]
@llaske, I can do the other part of tooltip, if it's fine in this one, collaboratively 
I'm doing that in the Calculate Activity

**Comment by llaske** [comment]
@Vishalk91-4 sure, good idea. Synchronize yourself with @vcvedika on this.

**Comment by Vishalk91-4** [comment]
> @llaske I plan to address the tooltip localization by creating a separate issue and working on it independently, as at present I am unable to figure out a working solution.

@vcvedika, could you give the access, I have fixed the tooltip one partially

**Comment by vcvedika** [comment]
> Vishalk91-4

Yes I've given the access @Vishalk91-4

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1486

**Pull request closed without merging**
