### PR TITLE
Replaced webL10n to i18next in Paint Activity

### PR DESCRIPTION
**Pull request by Vishalk91-4**
This PR fixes issue #1378 

- [x] Webl10n replaced everywhere in Paint Activity
- [x] Tutorials checked, working Fine
- [x] Tutorials, converted to their languages
- [x] No conflicts

@llaske , could you please review it

### CODE REVIEW

**Comment by llaske** [comment]
Thanks.

There is two issues:

* [ ] The language file is load continuously

image

* [ ] The tooltip on buttons is not localized

image

On this former issue, I suggest you to read https://github.com/llaske/sugarizer-doc/issues/42#issuecomment-1777916993

**Comment by Vishalk91-4** [comment]
@llaske, added tooltip localization
fixed continous loading, could you please review it please

**Comment by llaske** [comment]
The continuous loading is still here on my side.

image

**Comment by llaske** [comment]
@Vishalk91-4  are you still working on it?

**Comment by Vishalk91-4** [comment]
> @Vishalk91-4 are you still working on it?

Yes, I'll fix it, got ill in the last 3 days, so couldn't contribute, getting back to it now

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1487

**Pull request closed without merging**
