### PR TITLE
Enabled clicking on abacus beads to move it #146

### PR DESCRIPTION
**Pull request by aditigupta17**
Earlier, the user had to drag the beads, now a single click sends the beads up and double-clicking on them brings them down.
peek 2018-01-15 20-54

### CODE REVIEW

**Comment by llaske** [comment]
Nice work but using double-click is a problem because it will not work on touch screen.
Another idea ?

**Comment by aditigupta17** [comment]
Oh yeah, didn't see that..any suggestions from your side?

**Comment by aditigupta17** [comment]
I just tried, it works well on touch screen as well, just double-tapping the bead is causing it to move down.

**Comment by llaske** [comment]
Hmmm. Not sure double-tap is a intuitive gesture on touch screens.
Is there a way to compute automatically (by deduction) the direction expected by an user ? A sort of AI that could know that when you click it's for move up or down.
If it's possible to do that without any error, let's try this. Else we could propose an automatic move on click/tap when there is no doubt about the direction expected and let the drag gesture when it's not possible to do the deduction.
What do you think?

**Comment by aditigupta17** [comment]
Ya, the latter sounds good. Working on it.

**Comment by ritjoe** [comment]
Is there any other behavior associated with a single click or a touch (long or short) on a bead beyond moving it?

**Comment by aditigupta17** [comment]
According to the changes made in the PR, a single click/tap should send the bead up and double click/double tap moves it down.

**Comment by ritjoe** [comment]
On Sun, Mar 04, 2018 at 03:01:11AM -0800, Aditi Gupta wrote:
> According to the changes made in the PR, a single click/tap should send the
> bead up and double click/double tap moves it down.

OK. I'm just wondering why not make a single click do both?

Or rather, the only option in either direction is "move to the other
position."

So why use one for one direction and the other for the other direction?

**Comment by aditigupta17** [comment]
peek 2018-03-05 08-52
There are a few types of abacii, (like the one shown in the gif) in which beads can move in either direction. So to differentiate that, different gestures are needed.

**Comment by llaske** [comment]
Thanks all for your analysis. So my first intuition is the right: we could propose an automatic move on click/tap when there is no doubt about the direction expected and let the drag gesture - since double-tap is not intuitive - when it's not possible to do the deduction.

**Comment by llaske** [comment]
Fixed by https://github.com/llaske/sugarizer/pull/277

**Pull request closed without merging**
