### PR TITLE
adding generation speed button

### PR DESCRIPTION
**Pull request by prakashujjwal1010**
This pr adds a feature in game of life activity to control generation speed( #380 ).
I have made a single toolbar button which shows the current generation speed as well and a user will have a set of allowed speed values (i.e 0.25x, 0.5x, 1x, 2x, 4x) and will have to click that button to switch between different speed values. 

Screenshot from 2019-09-30 23-09-16

Screenshot from 2019-09-30 23-09-29

Screenshot from 2019-09-30 23-09-38

Screenshot from 2019-09-30 23-09-40

Screenshot from 2019-09-30 23-09-46

### CODE REVIEW

**Comment by llaske** [comment]
Good job. See my comment here: https://github.com/llaske/sugarizer/issues/380#issuecomment-537972811

**Comment by prakashujjwal1010** [comment]
The single generation speed is replaced by a pallete.
Screenshot from 2019-10-05 16-12-24
Screenshot from 2019-10-05 15-49-45

**Comment by llaske** [comment]
Very nice.
Few remarks:
- The icon is very cool. Could you confirm it use an Open Source license (or Creative Common)?
- The palette don't close when the user click a second time on it. It stay open forever.
- When the speed is low there is a strange "jump" in generation (see video capture below)

golissue

**Comment by prakashujjwal1010** [comment]
after introducing a speed palette in game of life , I checked its working in mozilla firefox and it was working good there was no jumps etc

ezgif com-video-to-gif

But when i checked it in chrome I noticed that the speed palette is not working that is palette don't close user  clicked on it second time and after changing the speed value by the range input there was jumps as speed keeps oscillating between its initial value and new value, as @llaske noticed.

ezgif com-video-to-gif (1)

I add the testpalette(just like in [docs](https://github.com/llaske/sugarizer/blob/master/docs/tutorial_step8.md) in game of life and found that even this test palette got stuck i.e. don't close by clicking second time in google chrome.
But then i add the same testpalette in xor activity but here the test palette is working fine in google chrome.

ezgif com-video-to-gif (2)

i even  tried to add different types of palettes in game of life but all of them were getting struck.

**Comment by prakashujjwal1010** [comment]
i downloaded the speed icon from [here](https://www.svgrepo.com/svg/28222/speedometer) and I think we can use it .

**Comment by llaske** [comment]
I've worked on your issues and it appears that it's not related to your work.
In fact, it's related to a tricky issue related to the way the `main` function is called in the activity. The `main` was called in the `localized` event but this event could be called double times depending of the browser. This double call generated double board generation at the same time and two events listeners on your palette.
I've declared a specific issue on it and fix it here: https://github.com/llaske/sugarizer/issues/388
Retrieve this fix and resolve conflicts and it should work on your side too.

Thanks for the precision on the speed icon.

**Comment by llaske** [comment]
Nice job.
Few things:

- Regarding speed: initial speed should be slower. The minimum speed should be very slow (may be one generation by second). The higher speed is too fast. Note that you don't need to have a linear speed.
- Could you localize the "speed" label in the palette?
- Remove commented code in speedpalette

**Comment by llaske** [comment]
Very good work. Thanks.

**Pull request merged**
