### PR TITLE
Fixed tooltip localization in Reflection activity

### LINKED ISSUE #1508: Tooltips not localized in Reflection activity
Tooltips are not localized after migration to i18next.

Screenshot

Language was set to spanish in the above picture

### PR DESCRIPTION
**Pull request by VishnuVardhanBR**
Fixes #1508 
Tooltips are localized

Screenshot

### CODE REVIEW

**Comment by llaske** [comment]
Doesn't work for the robot button 

64Z9HBQ7eR

**Comment by VishnuVardhanBR** [comment]
Screenshot

I'm confused, it works on mine?

**Comment by llaske** [comment]
Interesting, you're right it works when the new instance is created from French.
But I've found the way to reproduce the issue:
- Switch to English in Sugarizer settings
- Launch a new Reflection instance
- Stop the instance
- Switch to French in Sugarizer settings
- Relaunch the previous instance: the issue is here.

**Comment by VishnuVardhanBR** [comment]
Pushed a commit? Is this fix fine? @llaske

**Comment by llaske** [comment]
Nice. Thanks.

**Pull request merged**
