### PR TITLE
Replaced Bootstrap-tour by IntroJs in Paint activity

### PR DESCRIPTION
**Pull request by disha1202**
#1090 
Replaced Bootstrap-tour by IntroJs in Paint activity

[screen-recorder-thu-sep-01-2022-14-54-08.webm](https://user-images.githubusercontent.com/58461801/187882830-e2c5ec65-797f-48cd-8ef1-6098350e3893.webm)

### CODE REVIEW

**Comment by llaske** [comment]
Sounds good but the position of the close button is not the same (too close of the right border).
Do you know why?

image

**Comment by disha1202** [comment]
> Sounds good but the position of the close button is not the same (too close of the right border). Do you know why?
> 
> image

This might be due to different versions of IntroJs. I have used the latest one.
Here's the reference for the changes that have been made to the css related to skip button https://github.com/usablica/intro.js/pull/1708/files#diff-61919747715934800867ffcb198d7e8a6450cb3fbd4c8902cd3afbbc807a6d60R287

**Comment by llaske** [comment]
Try to use the same IntroJS version than the one currently use in Sugarizer to ensure it solve the issue.

**Comment by disha1202** [comment]
Used the same version of IntroJs which is currently in use in Sugarizer

Screenshot from 2022-09-05 10-35-02

**Comment by abhishek-sultaniya** [comment]
Hello @disha1202 ,please can you tell which version of introjs did you use or how did you downgraded its version?

**Comment by disha1202** [comment]
> Hello @disha1202 ,please can you tell which version of introjs did you use or how did you downgraded its version?

Hi @abhishek-sultaniya, I was unable to access any of the previous versions of IntroJs from its official site. So I just copied introjs.css and intro.js files from MindMath activity.

**Comment by llaske** [comment]
Nice. Thanks.
@disha1202 could you send a PR to fix the close button issue in Moon too?

**Pull request merged**
