### PR TITLE
Update filter pallete in the paint activity

### LINKED ISSUE #1004: Paint activity, filter activity options not clear.
In the paint activity, under the filter activity there are two options. However, there is no tooltip explaining what they do nor the help button explains it during the tutorial. Suggesting a very minor enhancement, i.e. simple tooltips explaining what they do.

### PR DESCRIPTION
**Pull request by AnandChourasia007**
To include tooltips for the two options under the filter button.
Fixes #1004 
Before:
filter pallete before
After:
filter pallete after1
filter pallete after2

### CODE REVIEW

**Comment by llaske** [comment]
Why not but tooltips should be localized.

**Comment by AnandChourasia007** [comment]
Yeah, sure.
(BTW, I saw that in the translate.ini file, the translations for two languages are not yet done, instead plain english text is written there, the languages being german [de], and portuguese [pt].  Since its not expected to be done by contributors I dont think I should raise this as an issue. Will you please look into it?)

**Comment by AnandChourasia007** [comment]
> Why not but tooltips should be localized.

What exactly do you mean by localized? I assumed its about storing the tooltip text in a variable and fetching it from translate.ini or locale.ini. But then I saw, in the index.html file none of the buttons' tooltips text are defined in this way. Please tell me what 'localizing' tooltips means. 😓

**Comment by llaske** [comment]
> But then I saw, in the index.html file none of the buttons' tooltips text are defined in this way

All tooltips should be localized. It's a good opportunity to fix it.

**Comment by AnandChourasia007** [comment]
@llaske , please review the new commits.

**Pull request merged**
