### PR TITLE
solved issue #549(resize function error)

### PR DESCRIPTION
**Pull request by sarthak-g**
Issue #549 fixed.
Issue is due to changing id of div everytime we play game(without reloading).

### CODE REVIEW

**Comment by s-mag** [comment]
Oh thanks mate. I will check now...

**Comment by s-mag** [comment]
@sarthak-g there is a new error coming
see here..
Error2
Kindly fix this error as well...

**Comment by s-mag** [comment]
> @sarthak-g there is a new error coming
> see here..
> Error2
> Kindly fix this error as well...

This error arises if you call the resize function....

**Comment by sarthak-g** [comment]
@s-mag  error arises because you are trying to call resize method when the game is not started.
Note: resize method is only for resizing canvas(battlefield) when game is started.

**Comment by s-mag** [comment]
> @s-mag error arises because you are trying to call resize method when the game is not started.
> Note: resize method is only for resizing canvas(battlefield) when game is started.

Oh I see nvm
Thanks....

**Comment by s-mag** [comment]
But the old issue has not been resolved if you change modes 5-6 times the old error comes again in infinite loop.....

**Comment by s-mag** [comment]
No need to work on this issue I have fixed it..
Thanks

**Comment by sarthak-g** [comment]
> 
> 
> @sarthak-g No need to work on this issue I have fixed it..
> Thanks

Your function doesn't resize at all.

**Comment by sarthak-g** [comment]
> 
> 
> @sarthak-g But the old issue has not been resolved if you change modes 5-6 times the old error comes again in infinite loop..... without calling the resize function.

I have tried more than 5-6 times with changing modes everytime, it is working fine.

**Comment by s-mag** [comment]
The code worked fine...
But I altered it a little bit because I am adding fullscreen buttons and calling the resize function which was causing an error.

**Comment by sarthak-g** [comment]
You can't remove that part of code

> 
> 
> The code worked fine...
> But I altered it a little bit because I am adding fullscreen buttons and calling the resize function which was causing an error.


Your alteration doesn't resize properly.The part you removed is to make sure that keyboard does not overlap with canvas.

**Comment by s-mag** [comment]
Ohk. Then I should create a zoom function for the fullscreen issue.
Thanks.

**Comment by llaske** [comment]
It works. Good job @sarthak-g and @s-mag.

**Pull request merged**
