### PR TITLE
Neighborhood view & UI Enhancements 

### PR DESCRIPTION
**Pull request by UtkarshSiddhpura**

### CODE REVIEW

**Comment by UtkarshSiddhpura** [comment]
Screen demo:
- Users and activities on the server
- Search by username or activity you're interested in
- Refresh if disconnected from server
- Sugarizer contributors

NV

Connect to server in App

App

**Comment by llaske** [comment]
The activity icon should disappear when no user are connected:

image

**Comment by UtkarshSiddhpura** [comment]
✅ Activities on screen with no users 
✅ `file:///` not showing server not set 3

### You can merge this PR i'll open another PR for `icon` Component issues

**Comment by llaske** [comment]
Few remarks:


* [ ] The icon for join popup should be colored like in v1

M926p1nyw0

* [ ] The handling of server connection in file:/// mode seems incompatible with v1

gT5IX80q0w

**Comment by llaske** [comment]
* [ ] Sounds like activities icons could be lost on slow network

9kPsgdP4gZ

**Comment by UtkarshSiddhpura** [comment]
> * [x]  The icon for join popup should be colored like in v1
 
> * [ ]  The handling of server connection in file:/// mode seems incompatible with v1

The handling is like v1 but i guess you already have saved setting for user server in local storage that's why the server is already set.

serverset

**Comment by UtkarshSiddhpura** [comment]
> * [ ]  Sounds like activities icons could be lost on slow network

I cannot reproduce the issue on fast3G and not even on slow3G

slow3

**Comment by llaske** [comment]
> The handling is like v1 but i guess you already have saved setting for user server in local storage that's why the server is already set.

I don't understand your point: the local storage is share between v1 and v2 so if it's set in v2 it should be set for v1. So refreshing the page in v1 should do the same in v2.

Oy709EKM1Z

**Comment by llaske** [comment]
>  I cannot reproduce the issue on fast3G and not even on slow3G

Hmmm. I reproduce it each time.
Steps to reproduce:
- Open Sugarizer in a browser, connect an user and share an activity
- Open a private browser window, open Sugarizer and connect with another user
- Go to Neighborhood view: everything is okay
- Change network to Fast 3G
- Refresh the page: the app icon is missing

o5L8lbPZ1A

**Comment by UtkarshSiddhpura** [comment]
> * Open Sugarizer in a browser, connect an user and share an activity
> * Open a private browser window, open Sugarizer and connect with another user
> * Go to Neighborhood view: everything is okay
> * Change network to Fast 3G
> * Refresh the page: the app icon is missing

Using chrome (The icon is there i forgot to record the full screen!)
nw

**Comment by UtkarshSiddhpura** [comment]
> I don't understand your point: the local storage is share between v1 and v2 so if it's set in v2 it should be set for v1. So refreshing the page in v1 should do the same in v2.

It works now (also clear the local storage for a fresh start)

**Pull request merged**
