### PR TITLE
Replaced Bootstrap tour by IntroJs in Curriculam Activity

### PR DESCRIPTION
**Pull request by ABHINAV-JHA-27**
Migrated Curriculam Activity from Bootstrap Tour to IntroJs https://github.com/llaske/sugarizer/issues/1090

### CODE REVIEW

**Comment by ABHINAV-JHA-27** [comment]
Hey @llaske , can you please have a look

**Comment by llaske** [comment]
Two issues:

* [ ] The header has not the same height than in other activities.

image


* [ ] On the Trophy popup there is only one button.

image

**Comment by ABHINAV-JHA-27** [comment]
Hey @llaske , I have solved the Padding issue But for the trophy issue, its happening because there is only 1 step for the introduction so it just shows next. should it have both??

**Comment by UtkarshSiddhpura** [comment]
@llaske Yes, for one step it'll only show one button done/next
see: https://github.com/usablica/intro.js/issues/1101#issuecomment-746287995

**Comment by llaske** [comment]
> But for the trophy issue, its happening because there is only 1 step for the introduction so it just shows next. should it have both??
It's better to show two buttons. @disha1202 found a work around [here](https://github.com/llaske/ExerciserReact/pull/143). May be you could do the same thing

**Comment by llaske** [comment]
Fixed by https://github.com/llaske/sugarizer/pull/1286

**Pull request closed without merging**
