### PR TITLE
Tutorial documentation update

### PR DESCRIPTION
**Pull request by NikhilM98**
I was going through the Pawn Activity tutorial. I found out that on adding every new pawn, whole `pawns` div is being re-rendered.
Suppose if you're adding N pawns one at a time, then the pawn div gets reset N times and a new pawn div is added N! (N factorial) times. It has a significantly higher time complexity than adding one pawn at a time which has a time complexity proportional to N.
When neighbor connects, I've kept in mind to clear the canvas and draw all the pawns in one go.

I have made appropriate changes in the documentation, keeping it simple.
I'm open to suggestions if you find any issue with my implementation.

### CODE REVIEW

**Comment by llaske** [comment]
It's just a pedagogic sample to learn how to develop a Sugarizer activity. It's not intended to learn good programing practice. So the source code should be as simple as possible.
It's not pertinent to add complexity if it's not related to the pedagogic objective.

**Comment by llaske** [comment]
It's just a pedagogic sample to learn how to develop a Sugarizer activity. It's not intended to learn good programing practice. So the source code should be as simple as possible.
It's not pertinent to add complexity if it's not related to the pedagogic objective.

**Comment by NikhilM98** [comment]
@llaske I have gone through the tutorial and I understand that its objective is to make users understand the basics of creating Sugarizer web activity. The tutorial is well written and is easy to understand even by new programmers.
I made changes, keeping the code simple. My objective was to make it clear to the users that they do not need to re-render the whole div again even as in the case of HTML canvas where the whole canvas is reset after every frame and `requestAnimFrame()` function is called. Its not about providing explicit documentation about time complexity and rendering optimization concepts, since this tutorial is one of a kind and it would also be used by Moderate/Advanced users, hints are provided in the code that will be out of sight of users who are not familiar with these concepts. Keeping the changes minimal.

**Comment by llaske** [comment]
You're wrong, the board is  not a Canvas HTML object, it's just a div object so there is nothing like a refresh process on every frame. So no need to add complexity here.

**Comment by NikhilM98** [comment]
Sorry @llaske I think I made a typo in the last comment.

> My objective is to make it clear to the users that they do not need to re-render the whole div again as in the case of HTML canvas

I was trying to say "Unlike Canvas".
I think someone reading the documentation can probably develop an understanding that to update a parent div, he has to clear it and then start creating its child nodes again. I was trying to make it clear to the user that this is not the case.

**Comment by llaske** [comment]
> I think someone reading the documentation can probably develop an understanding that to update a parent div, he has to clear it and then start creating its child nodes again.

I'm not agree. Understanding of JavaScript and DOM is a pre-requisite to write a Sugarizer activity. I don't expect to give good JavaScript practice in this tutorial. Focus is on specific Sugarizer mechanism, not on JavaScript way of working.

**Comment by NikhilM98** [comment]
Thanks for the response @llaske
I think I should close this PR if the understanding of JS and DOM is a pre-requisite for the user.

I was trying to make PR on Exerciser but no one has reviewed them so far. Can you please review [them](https://github.com/llaske/ExerciserReact/pulls)

**Pull request closed without merging**
