### PR TITLE
Added functionality to save Maze level in Journal and a new button in the toolbar to restart the game

### PR DESCRIPTION
**Pull request by lohani2280**
Right now I have added a new button in the toolbar to restart the game. I'll very soon add the fix for saving the Maze level in journal.

In the gif below, I have tried to demonstrate the behaviour of **restart** button.
restart_2

Refers https://github.com/llaske/sugarizer/issues/260

### CODE REVIEW

**Comment by lohani2280** [comment]
In the gif below, I have tried to demonstrate the functionality to save Maze level in Journal
stop

**Comment by lohani2280** [comment]
In the gif below, I have tried to demonstrate the behaviour of the restart button(as expected).
restart_3

Please let me know your views on this.

**Comment by llaske** [comment]
Hmmm. Sounds good except for the icon.
The idea was to use the Maze icon and add it the star that means new game. You've just copied the new icon button from Memorize activity. It's like clicking on this button will create a new memorize game...

**Comment by lohani2280** [comment]
@llaske Sorry about this. I understood now. I'll update it soon.

**Comment by lohani2280** [comment]
@llaske  I have updated the PR as suggested. Please have a look at it.

screenshot from 2019-02-07 21-45-11

**Comment by llaske** [comment]
It's perfect. Thanks.

**Pull request merged**
