### PR TITLE
Dollar activity Bootstrap Tour to IntroJS Tour

### PR DESCRIPTION
**Pull request by VedantSharma11**
hey @llaske 
I have Replaced Bootstrap tour with intro JS tour. please review
issue:https://github.com/llaske/sugarizer/issues/1090

image

### CODE REVIEW

**Comment by llaske** [comment]
Your PR include both change in DollarStreet and in Flip activity. Please do not mix change in PR.

**Comment by VedantSharma11** [comment]
@llaske  actually i have made 2 PR  first is for flip activity (LINK: https://github.com/llaske/sugarizer/pull/1231) in this i have changed code for just the flip activity and then i created PR for dollar activity merged with flip. So pls review my flip activity first

**Comment by llaske** [comment]
@VedantSharma11 Look like you've closed the PR regarding Flip: https://github.com/llaske/sugarizer/pull/1227
A good practice is to create a different branch for each PR.

**Comment by VedantSharma11** [comment]
@llaske check this PR https://github.com/llaske/sugarizer/pull/1231

**Comment by VedantSharma11** [comment]
@llaske  actually i had created a new PR for flip activity so please referr PR no:https://github.com/llaske/sugarizer/pull/1231

**Comment by VedantSharma11** [comment]
Alright @llaske I am closing this PR and making a new one with a different branch

**Pull request closed without merging**
