### PR TITLE
Localization for Clock activity

### PR DESCRIPTION
**Pull request by tradzik**
I have implemented full localization of Clock Activity, including dates display, using webL10n built into sugar webcore.

### CODE REVIEW

**Comment by i5o** [comment]
To be honest I thought this was impossible (lawl!)

Good job. Is this a GCI task or something?

**Comment by tradzik** [comment]
Thanks @i5o ! Then I even more happy because of my job. Yeah, it is based on a GCI task.

**Comment by llaske** [comment]
Very good job. BTW It could be nice to detect automatically the language. You could retrieve code for that in getSettings method of TankOp https://github.com/llaske/sugarizer/blob/master/activities/TankOp.activity/settings.js#L5

**Comment by tradzik** [comment]
Thanks! I have implemented the getSettings() in TankOp, I am gonna add it
also here. It is useful if remembered settings are different from the
current navigator (browser) settings.

**Comment by llaske** [comment]
Don't forget to take the task in GCI !

**Comment by tradzik** [comment]
Thank you, I will claim it soon! I have added getSettings and squashed commits. IMHO it is now mergable :smile:

**Pull request merged**
