### PR TITLE
[Activity Port] Implode activity for sugarizer

### PR DESCRIPTION
**Pull request by sarthak-g**
This is an initial build of Implode game for issue #710. Adding this to get an initial review on the progress made so far.

Yet to implement:

- [x] Journal connectivity
- [x] tutorial
- [x] Fullscreen
- [x] Localization
- [x] Popup box using picoModal or smiley face(as in python version) for Game Over

Will this game contain multiplayer mode?

### CODE REVIEW

**Comment by sarthak-g** [comment]
Implode Initial Demo

**Comment by quozl** [comment]
Hi.  I'm maintainer of the Python activity Implode.  Your video shows an instance of four blocks; three cyan and one blue, being dismissed by a single click.  That's not a valid move.  Please check carefully you have the logic working properly by running the Python activity as a test.  Also, the initial state of some of the games in the video seem remarkably regular; most games in the Python activity have an irregular cityscape.

**Comment by quozl** [comment]
I've looked again; the blue block should have been animated to fall, but the video does not show this.  Are you having the blocks fall properly?

**Comment by sarthak-g** [comment]
> Are you having the blocks fall properly?

Yes, it is there but not visible in the video.



> 
> Also, the initial state of some of the games in the video seem remarkably regular; most games in the Python activity have an irregular cityscape.

I've fixed dimensions in this activity 
8x6 for easy
12x10 for medium
20x15 for hard
Should I change it back as there in python version according to the area with above as minimum dimension?

**Comment by quozl** [comment]
> > Are you having the blocks fall properly?
> 
> Yes, it is there but not visible in the video.

Thanks.

> > Also, the initial state of some of the games in the video seem remarkably regular; most games in the Python activity have an irregular cityscape.
> 
> I've fixed dimensions in this activity
> 8x6 for easy
> 12x10 for medium
> 20x15 for hard
> Should I change it back as there in python version according to the area with above as minimum dimension?

I've no opinion about the dimensions.  My point is that the skyline is mostly flat in what you demonstrated, but when I test the Python activity (again just now), the skyline is almost never flat.

**Comment by quozl** [comment]
Is there any reason you cannot use the colours as used by the Python activity?

**Comment by sarthak-g** [comment]
> I've no opinion about the dimensions. My point is that the skyline is mostly flat in what you demonstrated, but when I test the Python activity (again just now), the skyline is almost never flat.

It is not always flat. See in the image below: 
hard level




> 
> 
> Is there any reason you cannot use the colours as used by the Python activity?

No, I previously used buddy color background due to which block color mixes with background color but after making background as black I forgot to update the changes.
I will correct it in the next commit.

**Comment by quozl** [comment]
Thanks.

**Comment by llaske** [comment]
Very good start. Nice to see it in Sugarizer.

Few remarks:
- The board should always be centered and should always use the maximum possible screen size
- Will be nice to add a redo icon too, like in the initial game
- Use splitbar between icons, see [here](https://github.com/llaske/sugarizer/blob/dev/activities/LabyrinthJS.activity/index.html#L49)
- Remove the vertical scrollbar
- I'm not a big fan of the popup at end, may be you could find another way to signal end of game (win or loss)
- Try to be uniform on indentation style (not the same between all sources files)

**Comment by sarthak-g** [comment]
> The board should always be centered and should always use the maximum possible screen size

By this you mean board should always use maximum height, right?

**Comment by quozl** [comment]
Tested d0d925e on Ubuntu 20.04 with Sugar 0.117 using `sugar-activity-web`.

* [ ] generated boards sometimes cannot be solved; the algorithm must generate solvable boards always,
* [ ] "You Won!!" is entirely different to the winning smile of blocks,
* [ ] blocks do not animate as they fall,
* [ ] board is not centred,
* [ ] a scroll bar is drawn on the right edge of display,
* [ ] the outline mouse-over highlight does not fill the space between blocks, and is not white, (it is pink),
* [ ] the outline mouse-over highlight occurs for blocks that cannot be dismissed; it should not occur, (this highlight is intended to indicate which blocks will be dismissed on click, and that can't happen for blocks of less than two of a colour),
* [ ] clicking in the area between blocks does not dismiss them; it should,
* [ ] when a set of blocks is dismissed, and the cursor is left inside the next set of blocks to be dismissed, they are not highlighted and a click does not dismiss them; as if you have depended on mouse movement alone rather than mouse movement or position.
* [ ] the single-dot mouse-over highlight does not occur,
* [ ] the skyline of new games tends to be more fully filled than expected,
* [ ] pressing the enter key repeats the last toolbar button press.

Plenty more observations can be made; please make sure you have both read the Python source code of Implode and that you have tested it yourself using Sugar.  https://github.com/sugarlabs/implode-activity

**Comment by sarthak-g** [comment]
> Plenty more observations can be made; please make sure you have both read the Python source code of Implode and that you have tested it yourself using Sugar. https://github.com/sugarlabs/implode-activity

Thanks @quozl for review. I've tested python version on sugar.

This is the initial build and a lot of things have to be improved. I will give activity same functionality and UI as python version.

**Comment by sarthak-g** [comment]
> Tested [d0d925e](https://github.com/llaske/sugarizer/commit/d0d925e9a191f35efec280d3d9c7d8f5e48883b4) on Ubuntu 20.04 with Sugar 0.117 using `sugar-activity-web`.

@quozl can you please tell steps for testing js activity on sugar.

**Comment by sarthak-g** [comment]
There are some cases in which the unsolvable board generates.  Due to this, you may find board in left hand time sometimes. I'm working on board generation. Rest of the features I've implemented.
@llaske please review it.

**Comment by llaske** [comment]
That's very good!

Few remarks:
- In Touch mode the game doesn't work very well because it's always the selected block that disappear and you can't change selection (no mouse over event).
- On small devices (try iPhone6/7/8 on Chrome responsive mode), the fullscreen button is not visible. It should be. May be you could reduce toolbar left padding (see [here](https://github.com/llaske/sugarizer/blob/dev/activities/SharedNotes.activity/css/activity.css#L350)) or remove splitbar in this case, to be sure it could be visible.

**Comment by sarthak-g** [comment]
- Fixed fullscreen button for small devices
- jquery library update
 
Suggestion for touch mode: single click for highlighting and double click for disappear
@llaske your views?

**Comment by llaske** [comment]
@sarthak-g I guess it's not really a double click but clicking on an already highlighted block?

**Comment by sarthak-g** [comment]
By double click, I mean two clicks simultaneously.
One click will highlight and then double click will disappear blocks

**Comment by llaske** [comment]
Sounds good.

**Comment by sarthak-g** [comment]
By mistake, I deleted previous comment

**Comment by sarthak-g** [comment]
@llaske changes done for touch mode.
Refresh is required after changing from desktop to mobile or vice versa in browser.

**Comment by llaske** [comment]
It's very cool!

Just two remarks:
- When doing unfullscreen on the winning screen, a scrollbar appear (see below):

Peek 05-05-2020 22-03

- Could you add help on board size buttons too?

@quozl any other suggestion?

**Comment by sarthak-g** [comment]
>   * When doing unfullscreen on the winning screen, a scrollbar appear
>   * Could you add help on board size buttons too?

@llaske made required changes

**Comment by llaske** [comment]
Thanks. It's fixed.

I've tested on a real touch device (may be you could do the same using [Sugarizer APK builder](https://github.com/llaske/sugarizer-apkbuilder)).
There is an issue regarding the touch: it seems that you're considering only double touch on the exact same block. But on a real touch device, it's hard to touch always on the exact same block - specifically on the large board where blocks are smaller. Could you consider double click on the same already selected **group of blocks**?

**Comment by sarthak-g** [comment]
@llaske we can also do one thing, double tap anywhere on the canvas will remove highlighted blocks(not just on the highlighted group). So, first click will highlight similar color blocks and then double tap anywhere on canvas will remove highlighted blocks.

**Comment by llaske** [comment]
Hmmm. Yes but the issue is more on removing blocks than removing selection.
You have sometimes to triple click (or more) to remove a block: the first click select a block and the block group, the second click select another block - in the same group - near the first one (but don't remove the group because it's not the same block than the first time), the third click - if you're lucky - you click on the second block again and the selected group is removed.

**Comment by sarthak-g** [comment]
> Yes but the issue is more on removing blocks than removing selection.

Yes, double tap anywhere on canvas will remove blocks

**Comment by llaske** [comment]
> Yes, double tap anywhere on canvas will remove blocks

No, not anywhere. Only in a block in the same group block that the current selected group.

**Comment by sarthak-g** [comment]
I've tried it on mobile using sugarizer APK.
Single tap highlight boxes corresponding to tapped box and double tap removes group.
Whenever double tap is done, it first brings circle to the box and then remove the group automatically.
In video below, first click highlight violet blocks group and then double tap on group remove all blocks
ezgif com-video-to-gif (3)

**Comment by sarthak-g** [comment]
Updated board generation
- [x] generated boards sometimes cannot be solved; the algorithm must generate solvable boards always
- [x] the skyline of new games tends to be more fully filled than expected

**Comment by llaske** [comment]
I've tested again on a tablet. As I said, only a double touch on the exact same block remove the current group:

ezgif-3-e83a346d11b1

There is no something as a double-click in touch mode. It's just touching two times on the exact same place. But it's a difficult gesture to do because touch precision is not the same than click precision.
It's why I suggest to update the way of working in touch mode: the first touch select the group, the second touch remove the selected group.

**Comment by sarthak-g** [comment]
> the first touch select the group, the second touch remove the selected group.

Updated controls of touchscreen according to this

**Comment by llaske** [comment]
Works very good. Thanks.
I'm going to continue my testing.

**Comment by llaske** [comment]
One thing: could you add a NOTICE file with your copyright? The process to do so is:
- Copy the original LICENSE file (I guess it's already the case for you) from [here](https://github.com/llaske/sugarizer/blob/dev/activities/ActivityTemplate/LICENSE),
- Copy the NOTICE file from [here](https://github.com/llaske/sugarizer/blob/dev/activities/ActivityTemplate/NOTICE)
- Update the NOTICE file with 2020 instead of [yyyy] and your name instead of [name of copyright owner]

**Comment by sarthak-g** [comment]
@llaske added NOTICE file

**Comment by llaske** [comment]
Nice. I've merged it.
Thanks a lot to port this activity to Sugarizer. Very good job.

**Pull request merged**
