### PR TITLE
Fixed selection of popup-title in language settings

### PR DESCRIPTION
**Pull request by Vishalk91-4**
@llaske 

Fixes en language issue #1546 
Also added time lapse as the popup was getting removed instantaneously when cursor was removed

https://github.com/llaske/sugarizer/assets/116670999/915df224-c9bc-4204-8a1a-ec493208b42c

Coud you please review it

### CODE REVIEW

**Comment by llaske** [comment]
Not a big fan of this fix: if it's not found it means that it's English.
I think that there is an error in the current implementation: English should be the title.
I suggest a fix by updating only one line, the one to activate the title:

image

**Comment by Vishalk91-4** [comment]
@llaske 
Yes that seems better
I thought in other way to set this as default, but yes the one you mentioned works

**Comment by llaske** [comment]
Okay.
Please remove the timer part since it's not needed.

**Comment by llaske** [comment]
Please, change only the updated file.

**Comment by Vishalk91-4** [comment]
> Please, change only the updated file.

Yes, Sorry, some local changes got into it
Fixed it now

**Comment by llaske** [comment]
Nice. Thanks.

**Pull request merged**
