### PR TITLE
improvement in "Missing flag handling in ColorMyWorld" issue

### PR DESCRIPTION
**Pull request by hharshas**
Added a condition to display name only if flag is not defined. #1603 @llaske

### CODE REVIEW

**Comment by llaske** [comment]
Sounds nice.
BTW I've just checked and the matching Emoji exist: https://emojipedia.org/flag-st-vincent-grenadines 
It's probably a name mismatch with the one declared in `flag.js`: https://github.com/llaske/sugarizer/blob/dev/activities/ColorMyWorld.activity/lib/flag.js#L221
Should be interesting to fix it and to ensure there is no mismatch in the flag list.

> [Fun with flags](https://bigbangtheory.fandom.com/wiki/Sheldon_Cooper_Presents:_Fun_with_Flags) :laughing:

**Comment by llaske** [comment]
@hharshas do you still work on this PR?

**Comment by hharshas** [comment]
Naah @llaske I am busy rn, you can assign it to others.

**Comment by piyushmishraa** [comment]
hi i would like to work on this issue ...can you assign it to me please ?

**Pull request closed without merging**
