### PR TITLE
updated speak activity

### PR DESCRIPTION
**Pull request by Ydvaaman**
hey @llaske 
I have updated the code for the Speak activity so that the separator separating the text box and the activity container spreads across the entire width of the screen.

Screenshot (28)

### CODE REVIEW

**Comment by prakharSrivs** [comment]
Hi @Ydvaaman, It looks like the PR is created in the wrong branch. 
Refer to contribution  guidelines at
 https://github.com/llaske/sugarizer/blob/master/CONTRIBUTING.md

**Comment by Ydvaaman** [comment]
sorry mistakenly  I raised PR  on the wrong branch so I am closing this PR so that I can raise it on the correct branch

**Comment by Ydvaaman** [comment]
Hey @prakharSrivs can you please explain how to raise the PR correctly

**Comment by prakharSrivs** [comment]
Check the Contribution Guidelines in the readme or check the below link
 https://github.com/llaske/sugarizer/blob/master/CONTRIBUTING.md

**Comment by Ydvaaman** [comment]
@prakharSrivs thnx for the help I got it👍

**Pull request closed without merging**
