### PR TITLE
Added delete button for recordings in record activity

### PR DESCRIPTION
**Pull request by Scar26**
Fixes: #344 

Before:
record1

Now:
record

### CODE REVIEW

**Comment by llaske** [comment]
This UI will be unusable on tablet, the icon is too small.
Could you suggest another UI?

**Comment by Scar26** [comment]
Would it be appropriate if the button appeared at the corner of the image popup?

Kind of like this:
UI

**Comment by llaske** [comment]
Good idea to put it in the detailed view.
BTW, it's not the standard Sugar icon for delete. Use [this one](https://github.com/llaske/sugarizer/blob/dev/activities/SharedNotes.activity/icons/delete-mode.svg) instead.
Plus, should be white, not red.

**Comment by Scar26** [comment]
Done @llaske 
Now:
record2

**Comment by llaske** [comment]
Nice. 
Please remove the confirm dialog box. I think it's not need. Plus if we want to do a confirm dialog box, the UI is incorrect it should be done with icons for non reading children.

**Comment by Scar26** [comment]
Ok, I have removed the confirm button.

**Comment by llaske** [comment]
Ok nice. Thanks.

**Pull request merged**
