### PR TITLE
Fix selectbox tests

### PR DESCRIPTION
**Pull request by UtkarshSiddhpura**

### CODE REVIEW

**Comment by llaske** [comment]
Could you fix conflicts?

**Comment by llaske** [comment]
There is still warnings and issues in the sandbox

image

**Comment by UtkarshSiddhpura** [comment]
> There is still warnings and issues in the sandbox
Resolved, the sandbox is working fine in feature/v2, I pushed the wrong changes

**Comment by llaske** [comment]
>  Should i resolve the warnings too?, It's mostly related to passing wrong prop data type, which i already fixed before for other screens, but not sandbox

Yes please.

**Comment by llaske** [comment]
There is still issues on the selectBox:

5o5r2qb6v1

**Pull request merged**
