### PR TITLE
Add tutorial for Constellation activity

### PR DESCRIPTION
**Pull request by sdziuda**
Added the tutorial for Constallation activity

### CODE REVIEW

**Comment by llaske** [comment]
Look like there is a missing style, the header has not the right color.

image

Should be a darker gray and text color should be write.
Are you sure you've copied all the CSS styles?

**Comment by sdziuda** [comment]
I think it should be fine now. There was probably one line left in code before the title class in css that was making this issue happen.

**Comment by llaske** [comment]
There is still an issue the fullscreen/unfullscreen button is now invisible

**Comment by sdziuda** [comment]
Ok, I've resolved this issue.

**Pull request merged**
