### PR TITLE
Fixed Resize issue in description of activities [continuation from 1366]

### PR DESCRIPTION
**Pull request by Vishalk91-4**
@llaske 
Fixed the resize issue, will close #1366 , since it had lot of issues ( created fresh PR ), was one of my firsrt PRs, thanks for your guidance on the issue at that time

Could you please review it here

### CODE REVIEW

**Comment by llaske** [comment]
Not sure to understand why you've done 2 PR.

**Comment by Vishalk91-4** [comment]
> Not sure to understand why you've done 2 PR.

Actually the time, I raised the first PR, I was new so used master branch, so now these activities are not present in that fork, that is what is raising conflicts, there, so 
It was easier if you merge this and close that one

**Comment by llaske** [comment]
So please close the one you want.

**Comment by Vishalk91-4** [comment]
@llaske, closed the previous one

**Comment by llaske** [comment]
Nice. Thanks @Vishalk91-4

**Pull request merged**
