### PR TITLE
Blockrain activity version 1.0

### PR DESCRIPTION
**Pull request by DarkPrince304**
This PR has the complete activity Blockrain JS for sugarizer. It will work for both desktop and mobile sugarizer environment. @llaske Would like it to get this tested from you and everyone else. Please comment here if anything needs to be changed.

### CODE REVIEW

**Comment by DarkPrince304** [comment]
Thank you @llaske.

I would like to discuss something about the arrow buttons. I have positioned the arrow buttons like this for two reasons.

1. For different, rather smaller screen sizes the buttons may seem to overlap

2. For devices such as an ipad the person usually holds it using both the hands so in such a case using both hands would be easier I guess?

**Comment by DarkPrince304** [comment]
Just need your reviews about the positioning of the arrow keys but apart from that all the other changes have been done and ready. Would like your reviews @llaske @mikklfr :)

**Comment by llaske** [comment]
Very nice.
Still an issue however: when I'm resizing the window, horizontal and vertical scrollbar appears

image

**Comment by llaske** [comment]
Solve now.
Could you set as default the theme on my screen capture ?

**Comment by llaske** [comment]
Cool. I will test it in Android, iOS and Windows 10 to ensure it works then I will merge it.
Thanks for your work.

**Pull request merged**
