### PR TITLE
added watchit activity

### PR DESCRIPTION
**Pull request by akshat0047**
#297 
Added a prototype of how the activity would look in its initial form.
Please approve if I should proceed with the same.

### CODE REVIEW

**Comment by llaske** [comment]
I'm not able to play the game so don't understand how it works.
Could you explain?
Plus it's impossible to renew the game without restarting the activity.
Warning regarding the size of the activity: more than 20Mb already.

**Comment by akshat0047** [comment]
Playing Instructions
--------------------------
We have to trace the path between red lines with the cursor, it is easy as of now for a prototype but will be really challenging in upcoming levels due to animating obstacles.

Space Issue
-----------------
It is solved by removing unwanted libraries present in the directory

Renew Issue
-----------------
I will fix the renew thing as soon as possible by adding an option to restart the game but as of now I am facing this error randomly, soon after I add an activity.

Screenshot from 2019-03-21 02-11-26

**Comment by llaske** [comment]
Finally find the way to play.
It's too complex and will be unplayable on a touch screen where there is no something like a cursor.
Regarding your issue, I suggest you to fully clear your browser cache or typing "localStorage.clear()" on the browser console.

**Comment by akshat0047** [comment]
I'm unable to find a way to implement it on touch screen efficiently, can you suggest me one.

**Comment by akshat0047** [comment]
I am making the activity less complex and compatible by:-

1- Widening the path
2- Introducing a game object to move with onscreen controls(touch)/keyboard(desktop)

**Comment by llaske** [comment]
Not usable and not pertinent for the moment.

**Pull request closed without merging**
