### PR TITLE
Measure Activity: introjs popups fix

### PR DESCRIPTION
**Pull request by VedantSharma11**
## Video:
---

https://user-images.githubusercontent.com/96445392/223523498-6b370988-6dc2-4fb6-b743-1e9ef34e88e0.mp4

### CODE REVIEW

**Comment by llaske** [comment]
Why you need to change introjs library? The idea is to use the same in all activities.

**Comment by VedantSharma11** [comment]
@llaske Actually I have not changed the complete introjs library , It was *unformatted* so I *formatted* it and then just made few changes in the css file thats it

**Comment by llaske** [comment]
So resubmit the PR without introjs change.

**Comment by VedantSharma11** [comment]
@llaske okay I'm doing it

**Comment by VedantSharma11** [comment]
okay @llaske I will be raising a new PR then

**Comment by VedantSharma11** [comment]
@llaske I have made the changes please review them, If there is any issue please let me know

**Comment by VedantSharma11** [comment]
@llaske This time I have added my changes seperately in the `activity.css` file instead of editing the `introjs.css` library
pls review it & let me know if any changes are needed.

**Comment by VedantSharma11** [comment]
@llaske  This time I have added my changes seperately in the `activity.css` file instead of editing the `introjs.css` library
pls review it & let me know if any changes are needed.

**Comment by llaske** [comment]
Okay. Thanks.

**Pull request merged**
