### PR TITLE
fixes #556 responsiveness of TankOp activity

### PR DESCRIPTION
**Pull request by b18050**

### CODE REVIEW

**Comment by b18050** [comment]
Please check @llaske .

**Comment by llaske** [comment]
It don't solve the issue.

image

**Comment by llaske** [comment]
Check https://github.com/llaske/sugarizer/pull/573
It has no sense to be two developers to work on the same issue at the same time.

**Comment by b18050** [comment]
tankk_homepage
@llaske  I am getting this after adding this patch .So , Please tell me how to proceed further. I am using Firefox browser.

**Pull request closed without merging**
