### PR TITLE
created a chess activity

### PR DESCRIPTION
**Pull request by samcaspus**
created a chess activity against comp for Gsoc

### CODE REVIEW

**Comment by ashish0910** [comment]
@samcaspus there are a lot of unnecessary changes . You don't have to add Pawn.Activity in this Pull request . There should only addition of Chess activity and it's addition in activity.json . Please do not add any other changes .

**Comment by samcaspus** [comment]
@ashish0910  will make the changes.

**Comment by ashish0910** [comment]
@samcaspus please remove Pawn Activity from pull request .

**Comment by samcaspus** [comment]
@ashish0910 actually i have removed them if you see it says i have deleted all the files... let me know if i am interpreting it wrong.

**Comment by samcaspus** [comment]
due to issues with regards to file I have create a new pull request fixing the issue here at [#735](https://github.com/llaske/sugarizer/pull/735) hope that fixes all the issues @ashish0910

**Comment by quozl** [comment]
@samcaspus, while deleting your repository and starting again with a new clone, as you have done, **can work**, a more usual method is to fix the problem in the branch you are working on.  Next time, you might do better, by using git features, after searching for solutions.

**Pull request closed without merging**
