### PR TITLE
fix(MazeWeb): Add resize screen feature #421

### LINKED ISSUE #400: Add a fullscreen button in the Maze activity
The idea is to add a fullscreen button in the toolbar to increase the size for activities contents on small devices.

The complete process is describe in https://github.com/llaske/sugarizer/issues/399

### PR DESCRIPTION
**Pull request by felipebrunetti94**
- Add fullscreen and unfullscreen buttons to MazeWeb/index.html
- Add fullscreen and unfullscreen icons to MazeWeb/icons/
- Add fullscreen and unfullscreen function to MazeWeb/js/activities.js

Fix #400

### CODE REVIEW

**Comment by llaske** [comment]
It don't works, there is an error in the console during launch:

```
activity.js:4 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at activity.js:4
    at Object.execCb (require.js:1604)
    at Module.check (require.js:844)
    at Module.<anonymous> (require.js:1084)
    at require.js:129
    at require.js:1127
    at each (require.js:57)
    at Module.emit (require.js:1126)
    at Module.check (require.js:898)
    at Module.<anonymous> (require.js:1084)
```

Please provide a screen capture of your fix in the text of your PR. It will help us to answer more quickly.

**Comment by felipebrunetti94** [comment]
Sorry, I left a commit in behind kkk try it now. :smile:

**Comment by llaske** [comment]
The toolbar is hidden/shown correctly but the window is not resized.
You must resize the window to increase the board size.

**Comment by felipebrunetti94** [comment]
Sorry @llaske , but i don't get it, what do you mean by 'resize the window to increase the board size', the `display:none` wouldn't make the other elements of the window adapt to the new available space ?

**Comment by llaske** [comment]
Yes it adapt the other elements size but you should then resize content drawn by the activity into these elements to use the new space. See for example what happens when the window is resized: https://github.com/llaske/sugarizer/blob/dev/activities/MazeWeb.activity/js/activity.js#L179

**Comment by felipebrunetti94** [comment]
@llaske oooh, now I see...
I just pushed the changes, sorry about the delay.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/482

**Pull request closed without merging**
