### PR TITLE
Added SugarDevice component to Vue template

### PR DESCRIPTION
**Pull request by dhruvmisra**
Added new `SugarDevice` component with following features:
* Geolocation API
* Accelerometer support (through Cordova)
* Vibration API

Other:
* SugarL10n concurrency fix

### CODE REVIEW

**Comment by llaske** [comment]
Nice work. The inclusion of `cordova.js` is very smart.
Two remarks:
- It seems that some browsers support Accelerometer feature [natively](https://developer.mozilla.org/en-US/docs/Web/API/Accelerometer/Accelerometer). In this case, I think it's better to rely on it, else try to rely on Cordova feature.
- Warning: you mixed TAB/Space indentation style in this file.

**Comment by dhruvmisra** [comment]
I have added the support for native accelerometer whenever it will be available.

Also made changes to SugarL10n to emit the `localized`event after the activity has initialized. 
Working: Added an event listener for SugarAcitivty's `initialized` event which makes `activityInitialized` = true. Added a computed property `readyToEmit` which returns the logical AND of activityInitialized and (vm.dictionary != null) [set after localized event on window], and finally watching this property to emit the `localized` event when true.

**Comment by llaske** [comment]
Regarding accelerometer, do you confirm that the way of using the component will be the same in both case: Cordova and browser? Plus, I wonder it's not better, instead of having an `accelerator-callback` to have a `getCurrentAcceleration` method and let the user of this component decide when he want to get a new value.

Regarding SugarL10n:
- What happens if the activity is initialized before the SugarL10n component has opportunity to run `vm.$root.$refs.SugarActivity.$on('initialized',...` ? 
- It force the user to create the SugarActivity component and give it a reference name `SugarActivity`. It will be better to not force the user to use a specific reference name (or not set a reference name at all). To avoid this constraint, may be we could browse the `$root` property to search for `SugarActivity` component?

**Comment by dhruvmisra** [comment]
If the `accelerometer` object exists, it will be used even in mobile (Not sure about iOS) else the cordova watcher will be added. Let's add the `getCurrentAcceleration` as an additional method as I think the `watchAcceleration` is useful because usually the acceleration is required after a constant interval.

Regarding SugarL10n:
* This situation would not occur as the listener is added directly in the mounted life-cycle hook and being synchronous code, JavaScript Event Loop will complete it's execution before any asynchronous `requirejs` callbacks are resolved.
* In Vue.js the recommended way to access components is through `refs`, so the user should *always* include a ref to access it's methods, but you are right that the user might give some other ref name to the component which can cause issues. Let me see if I can search and attach the listener that way.

**Comment by dhruvmisra** [comment]
I have added a `name` property to SugarActivity and using it to attach the property in SugarL10n, This removes the dependency on ref name altogether.

Not adding the `getCurrentAcceleration` due to the incompatibility with Cordova.

**Comment by llaske** [comment]
Okay, nice.
I guess the tutorial step 5 should be changed to reflect this change.
I suggest to integrate it in the same PR.

**Comment by dhruvmisra** [comment]
Updated the tutorial step.

**Comment by llaske** [comment]
Nice. Thanks. It's better like that.

**Pull request merged**
