### PR TITLE
changing background colour of scroll bar in write activity

### PR DESCRIPTION
**Pull request by Ayeshashaik759**
I tried changing the background color of scroll bar in write activity by doing the following changes. Related to the issue #1181

### CODE REVIEW

**Comment by llaske** [comment]
Smart fix :+1: 
BTW I wonder if the issue could not be fixed in another way.
The Memorize activity use the same Journal component but don't have the issue:

Capture d’écran du 2023-02-09 22-18-28

**Comment by Ayeshashaik759** [comment]
Actually the background color of both are a little bit different.

Screenshot (5)

I inspected both the activities and observed that both have same properties but still difference occurs.

Screenshot (6)

I tried changing the opacity in write activity (by increasing the opacity from 0.5 to 0.66) then I observed that it is working fine and we can see the scroll bar.

Screenshot (16)

images compared after making changes to opacity in write activity.
Screenshot (11)

And we get this opacity from div with class "pico-overlay" which is an event present in the library lib/picoModal.js. I tried changing the opacity of class pico-overlay in activity.css by it is not working changes are not visible. And as we should not make changes to the libraries so @llaske  can you give suggest any idea to solve this.

Screenshot (17)

**Comment by llaske** [comment]
Thanks for this analysis.
Should be tested but may be forcing the opacity by adding following lines in `activity.css` could do the job:

```
.pico-overlay {
  opacity: 0.66 !important;
}
```

**Comment by Ayeshashaik759** [comment]
> Thanks for this analysis. Should be tested but may be forcing the opacity by adding following lines in `activity.css` could do the job:
> 
> ```
> .pico-overlay {
>   opacity: 0.66 !important;
> }
> ```

Yes it is working now got the output as expected. Shall I continue to do this changes for the remaining activities also In which this issue is occurring

**Comment by llaske** [comment]
> Shall I continue to do this changes for the remaining activities also In which this issue is occurring

Yes. Please do the change in the same PR and ensure everything works like expected.

**Comment by Ayeshashaik759** [comment]
Yah sure 😊

**Comment by llaske** [comment]
Nice. Thanks.

**Pull request merged**
