### PR TITLE
Chessboard Task for GSoC 2020

### PR DESCRIPTION
**Pull request by Hemansh31**
Initial commit for the Chessboard Task Challenge #592 for GSoC 2020

### CODE REVIEW

**Comment by ashish0910** [comment]
@Hemansh31 Looks Promising 
Few Remarks :
1. On playing smart mode the game hangs for few seconds maybe because of large calculations ( does not happen in any other mode though ) . 
2.May be we can show list of moves .

**Comment by Hemansh31** [comment]
@ashish0910 First of all Thanks for the remarks.
Secondly, when you say show the list of moves what is it that you expect because I have already shown all possible moves of a piece on mouse hover, is that not what you mean? Also yeah the smart mode is supposed to be the slowest as it is brute force backtracking without any alpha beta pruning.

**Comment by llaske** [comment]
Your PR contains content not related to this PR (Chat activity).
Please do one branch and one PR for each issue.

**Comment by Hemansh31** [comment]
@llaske I added that file by mistake but I removed it. Thanks for the remarks

**Comment by ashish0910** [comment]
> @ashish0910 First of all Thanks for the remarks.
> Secondly, when you say show the list of moves what is it that you expect because I have already shown all possible moves of a piece on mouse hover, is that not what you mean? Also yeah the smart mode is supposed to be the slowest as it is brute force backtracking without any alpha beta pruning.

By List of moves I mean maintaining a log of moves played by user

**Comment by llaske** [comment]
Good start. I specifically like your tutorial.

My remarks:

* The activity is not responsive
* Will be better to use a palette to select computer level
* You could use buddy color preference for background color
* Will be better to display a popup when an user join/leave the game (see in Memorize or Paint activity)
* Will be better to display buddy icon colors for opponent (see in Memory or LOL activity)
* The network icon should to the left, just after the activity palette
* The activity palette is empty when open, it should display the activity name by default
* Will be better to use an icon with a king instead of a pawn for the activity
* The message at the end of the game should not be a simple Javascript popup

**Comment by llaske** [comment]
Unfinished

**Pull request closed without merging**
