### PR TITLE
Fixed issue of PR #1229 , Changed Tour of XOEditor.activity from bootstrap to Intro.js

### PR DESCRIPTION
**Pull request by rockharshitmaurya**
Hey @llaske here is the fixed of PR No : https://github.com/llaske/sugarizer/pull/1229 please review my PR

### CODE REVIEW

**Comment by llaske** [comment]
The welcome screen popup is missing.

image

**Comment by rockharshitmaurya** [comment]
Ok @llaske I'm working on it

**Comment by rockharshitmaurya** [comment]
hey @llaske I have resolved the issue please review it

**Comment by llaske** [comment]
Nice. Thanks.

**Pull request merged**
