### PR TITLE
Increased the size of items(time, buttons) in StopWatch activity

### PR DESCRIPTION
**Pull request by lohani2280**
In the gif below, I have tried to demonstrate the fix
stopwatch
Fixes https://github.com/llaske/sugarizer/issues/261

### CODE REVIEW

**Comment by llaske** [comment]
Good start. But the font size for counter should be increase too and it should be vertically align at center. Guess it's auto-align on Firefox (on your screen capture) but it's not on Chrome or Safari.

capture d ecran 2019-01-24 a 21 34 26

**Comment by lohani2280** [comment]
@llaske Thanks for the review. I'll update the PR as per the suggestion very soon.

**Comment by lohani2280** [comment]
@llaske I have updated the PR as suggested. The fond size for counter is increased and its now vertically align at center as shown below. 

screenshot from 2019-01-25 21-27-13

**Comment by llaske** [comment]
It's better but it's not perfectly center.
My wish is to have:
- The counter vertically centered in the middle of the line
- The button group vertically centered in the middle of the line

Here's how it's displayed on Chrome, Firefox and Safari. It's not centered and it's centered differently from a browser to another.

image

Could you find a way to do better?

**Comment by lohani2280** [comment]
@llaske Sure. I'll try my best to make it better and will get back soon.

**Comment by lohani2280** [comment]
This time I tried to make it perfectly centered. I tested it on chrome and firefox and found that this time they are centered in same manner.

Here's how it's displayed on Chrome.
screenshot from 2019-01-29 23-04-50

Here's how it's displayed on Firefox.
screenshot from 2019-01-29 23-17-05

Please let me know your views on this.

**Comment by lohani2280** [comment]
Yeah, I noticed this side effect after synchronising the PR and that's why I edited my comment to <B> WIP</B>. I am now working on removing this side effect and will get back soon.

**Comment by lohani2280** [comment]
@llaske I have synchronized the PR. This time I tried to address the small size window issue.
This is how the app looks like when window size is small.
screenshot from 2019-01-30 13-08-53

This is how the app looks like when window size is large.
screenshot from 2019-01-30 13-21-47

Please let me know your views on this.

**Comment by llaske** [comment]
Look great now. Thanks.

**Pull request merged**
