### PR TITLE
Solved issue #404 (Handle resize in TankOp)

### PR DESCRIPTION
**Pull request by sarthak-g**
Window resize problem fixed as mentioned in issue #4
ezgif com-video-to-gif (2)

### CODE REVIEW

**Comment by llaske** [comment]
Nice.

It's a good idea to do a `resize` method but may be you could call it from the `create` method to avoid duplicate code.

Could you use a smarter algorithm? i.e. imagin an algorithm to compute the zoom level instead of using a list of if statements.

**Comment by sarthak-g** [comment]
I think algo below is good as compare to if statements:
wsize = document.body.clientWidth;
var ratio = Math.abs(wsize-100)/1000;  //statement 1
this.zoom = Math.max(ratio,0.4);  //statement 2
this.zoom = Math.min(this.zoom,1);  //statement 3
In statement 1, 100 is used because it is giving good results after trial and error from various screen sizes.
Statement 2 is to maintain zoom value greater than or equal to 0.4
Statement 3 is to maintain zoom value less than or equal to 1

**Comment by sarthak-g** [comment]
Is this approach good? Can I change it in create method also?

**Comment by llaske** [comment]
Hmmm. Not too bad but Could be better. Is there any way to be sure that the keyboard don't override the board?

**Comment by sarthak-g** [comment]
I subtracted window's width with the width occupied by keyboard and calculate zoom on the basis of remaining width.

**Comment by sarthak-g** [comment]
Is this approach good? or you can suggest some better way?

**Comment by llaske** [comment]
It's very good!
May be you could now factorize this algorithm to do the same in the the create method?

**Comment by sarthak-g** [comment]
Updated code in create method

**Pull request merged**
