### PR TITLE
Added Back Button in Gridpaint activity.

### PR DESCRIPTION
**Pull request by s-mag**
Fixed Issue #546 
@llaske I am making different PR for each Issue.
Closed previous PR.

Untitled

### CODE REVIEW

**Comment by llaske** [comment]
Nice.

Could you update the tutorial too? It still mention the "green circle"

image

I suggest to add a popup to point the new back icon.

**Comment by s-mag** [comment]
Oh I forgot that!! Will do that

**Comment by s-mag** [comment]
@llaske I have updated localization for the new back icon. I cannot add popup for it because it is also drawn in the same way as the other buttons [here](https://github.com/llaske/sugarizer/pull/565/files#diff-f00bf3e76d44a27c767deacc7c4cbc1dR221).

**Comment by llaske** [comment]
Nice. Thanks.

**Pull request merged**
