### PR TITLE
Added Nim Game, as was asked in https://github.com/sugarlabs/GSoC/blob/master/Ideas-2024.md#math-games

### PR DESCRIPTION
**Pull request by sonisumit7904**
@llaske, Sir, as it asked in : https://github.com/sugarlabs/GSoC/blob/master/Ideas-2024.md#math-games, I have created and deployed it on Sugarizer, please Review, and provide your insights!

# Web Nim

WebNimImage

Nim (game) that I made on the web.

# Live at :
https://sonisumit7904.github.io/NIM_Game_for_Web/

## Game Rule

There are several rows of coins below. Each player must pick a row and take at least one coin when it is player's turn. So the one **who takes the last coin** is the winner.

## Keyboard shortcuts

| Shortcut         | Action      |
| ---------------- | ----------- |
| `N`              | New game    |
| `Enter`, `Space` | Pass turn   |
| `Esc`            | Options     |
| `1`         | First row  |
| `2`         | Second row |
| `3`         | Third row  |
| `4`         | Forth row  |

### CODE REVIEW

**Comment by Vishalk91-4** [comment]
@llaske
Just to ask, we have Last one loses on Sugarizer which has similar concept to this right

**Comment by sonisumit7904** [comment]
> @llaske Just to ask, we have Last one loses on Sugarizer which has similar concept to this right

Objective:
Classic Nim: Last player to take an object wins.
Last One Loses: First player forced to take the last object loses.
Winning Strategy:
Classic Nim: Leave opponent with a single object.
Last One Loses: Leave opponent with a non-single object situation.
Outcome:
Classic Nim: Winner takes the last object.
Last One Loses: Loser takes the last object.

Gameplay difference:
Classic Nim: choose only 1 pile out of many, and delete any number of objects(atleast 1) in that pile
Last One Loses: Remove at most 3 objects and only 1 pile is present.

They feel same, as Last One Loses, is a variation of NIM, but winning strategy used is Different for each of them, and we 
Additionally, "Nim" encompasses a broader category with numerous variants beyond the classic version, and "Last One Out" is simply one such variation with a unique objective.

**Comment by llaske** [comment]
@sonisumit7904 once again the game is too basic with no clear pedagogical interest. For Sugarizer we tend to listen from teachers request and try to created activities related to the school curriculum. 
Plus I'm agree with @Vishalk91-4, it's very similar to LOL which is deprecated.

**Comment by sonisumit7904** [comment]
> @sonisumit7904 once again the game is too basic with no clear pedagogical interest. For Sugarizer we tend to listen from teachers request and try to created activities related to the school curriculum. Plus I'm agree with @Vishalk91-4, it's very similar to LOL which is deprecated.

@llaske ,Ok, I understand, then please suggest some games, which you think would be suitable, I can start working on them of you'd like.

**Comment by llaske** [comment]
The requested activity is 3D volume https://github.com/sugarlabs/GSoC/blob/master/Ideas-2024.md#sugarizer-3d-volume-activity

**Comment by sonisumit7904** [comment]
> The requested activity is 3D volume https://github.com/sugarlabs/GSoC/blob/master/Ideas-2024.md#sugarizer-3d-volume-activity

Thank you, I will start working on it.

**Pull request closed without merging**
