### PR TITLE
Fixing #133

### PR DESCRIPTION
**Pull request by kunal-mohta**

### CODE REVIEW

**Comment by kunal-mohta** [comment]
How should I send PRs for other issues fixed?
Should I create a separate branch for them?

**Comment by llaske** [comment]
No need to create a specific branch for a small fix. Just send a PR from the dev branch.
BTW do one different PR for each fix.

**Comment by kunal-mohta** [comment]
Sorry to bother, but that means at a time I can send a single PR for small fixes right?

**Comment by llaske** [comment]
One PR for each fix yes.

**Pull request merged**
