### PR TITLE
feat: added fullscreen button in Physics

### PR DESCRIPTION
**Pull request by NathanDimmer**
Adds the fullscreen button, fixing issue #410 

@utkarsh-raj @llaske @ashish0910 @FreddieN @mikklfr @eohomegrownapps

### CODE REVIEW

**Comment by llaske** [comment]
It doesn't work and when the fullscreen button is clicked, there is an error message on the console:

```
activity.js:136 Uncaught TypeError: Failed to execute 'dispatchEvent' on 'EventTarget': parameter 1 is not of type 'Event'.
    at HTMLButtonElement.<anonymous> (activity.js:136)
```

**Comment by NathanDimmer** [comment]
Fixed

**Comment by llaske** [comment]
There is a another issue, when clicking to unfullscreen button, a new item is created (see below)

Peek 21-12-2019 22-26

**Comment by NathanDimmer** [comment]
I fixed the issue!

**Comment by llaske** [comment]
Hmmm. I think there is an easiest solution. May be just calling a preventDefault on the unfullscreen button should solve the issue. Could you try?

**Comment by NathanDimmer** [comment]
Thank you so much, that is a much simpler solution. I'd never used that before!

**Comment by llaske** [comment]
Nice. BTW, I've just validated another PR on Physics. Could you fix conflicts?

**Comment by NathanDimmer** [comment]
Fixed!

**Pull request closed without merging**
