### PR TITLE
Fixes the Text Area Resize 

### PR DESCRIPTION
**Pull request by Vishalk91-4**
Fixes issue #1303 

Hi @llaske
All the Activities section which had the text description box have been resized vertically, basically few codes have been implemented in all activity sections individually. 
I have also made the boxes resized up to a certain height so that it does not overflow.

After Modification

https://github.com/llaske/sugarizer/assets/116670999/3087060f-ea3a-4556-8574-d9ee1e6232d4

### CODE REVIEW

**Comment by Vishalk91-4** [comment]
@llaske could you please review it.

**Comment by llaske** [comment]
Changing `textarea` style globally is risky: it will apply to the object in all activity so what if there is another `textarea` inside. It will be better to apply change only to this one.

No need to do change in `sugar-200dpi.css` and `sugar.less`.

**Comment by Vishalk91-4** [comment]
@llaske 
Do you need something like this, 
I'll add like description expand with it
textarea {
  resize: vertical;
  max-height: 70vh;
}
Should the things be added in css files outside or through every activity section

**Comment by Vishalk91-4** [comment]
@llaske , the fix I found was to add the textarea in either the activity.css of each activity or in activity.pallete.html of each activity, will that work, just one line in each is to be added

**Comment by llaske** [comment]
@Vishalk91-4 I think to target more precisely the `textarea` by prefixing hit by the full css path to it.
So even if there is another `textarea` in the activity, it will not match the css path.

**Pull request closed without merging**
