### PR TITLE
dollar-street activity works

### LINKED ISSUE #985: Dollar street activity not loading.
On clicking on the dollar street activity icon, a new page begins loading. But the loading never completes and an error is logged in the console, 'HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE'.

Dollar street activity not loading

However, the buttons 'filter by region' and 'see families' work perfectly fine.

https://user-images.githubusercontent.com/89119829/156038671-a04cae64-2553-4f0d-ae6f-ca4ee77e38ab.mp4

Also, the slider boundary values in the 'filter by income' button are set to NaN.
Slider limits issue

### PR DESCRIPTION
**Pull request by dhwaj1902**
fix #985 

https://user-images.githubusercontent.com/57860123/158677327-18f0b341-fbf7-4f4e-a5fa-23d73619186a.mp4

### CODE REVIEW

**Comment by codebloded** [comment]
@dhwaj1902  are you using static numbers instead of data from api?

**Comment by llaske** [comment]
It fix only a part of the issue. See [here](https://sugarizer.org/videos/dollarstreet.gif) for what's expected.
Plus hard coding it's not a good practice. I've suggested [here](https://github.com/llaske/sugarizer/issues/985#issuecomment-1069148164) to use one or more local JSON extracted from the current source code instead.

**Comment by dhwaj1902** [comment]
@llaske I have hard coded only the income which is hard coded on their site also, I guess there are two things left one is things filter and other is showing more info while on a particular family page.

**Comment by llaske** [comment]
@dhwaj1902 I'm expecting a fix for all malfunction in the activity.
Initializing street-settings, languages, region-filter and things-filter is very important for the activity.

**Comment by llaske** [comment]
I'm closing the PR due to lack of activity.
The issue https://github.com/llaske/sugarizer/issues/985 is major, I don't want this PR prevent other contributors propose a better solution.

**Pull request closed without merging**
