### PR TITLE
#1378 Replaced WebL10n to i18next in Markdown Activity

### PR DESCRIPTION
**Pull request by Rohan20-10**
@llaske pls review the pr
attaching ss of the results
# Replaced WebL10n to i18next in Markdown Activity
Screenshot 2024-01-19 091723

### CODE REVIEW

**Comment by llaske** [comment]
It doesn't work when the user language is unsupported (here Igbo). The activity is suppose to switch en English.

image

**Comment by llaske** [comment]
@Rohan20-10 are you still working on it?

**Comment by Rohan20-10** [comment]
> @Rohan20-10 are you still working on it?

@llaske I am working with that issue just give me a day I was busy with my clg exams.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/667e6dc1472010d949a7f50d30b8b2373ea6572c

**Pull request closed without merging**
