### PR TITLE
 Game of Life #1150 ~ Adding Drag to fill Cells Functionality

### PR DESCRIPTION
**Pull request by hharshas**
@llaske Changes to fill / Unfill based on mousedown / touchstart. I have also tried on the touch device using https://github.com/llaske/sugarizer-apkbuilder and everything seems fine. #1150

### CODE REVIEW

**Comment by llaske** [comment]
Nice but will be better to support both fill/unfill with move and also simple click/touch to fill one cell.
See for example how it works in Gridpaint activity.

**Comment by hharshas** [comment]
@llaske  added both click to fill and drag to fill feature

**Comment by llaske** [comment]
Just tested on a real tablet, that's very cool, thanks.

**Comment by hharshas** [comment]
> Just tested on a real tablet, that's very cool, thanks.

Same, Literally played for half an hour after this change, felt great too 🙃

**Pull request merged**
