### PR TITLE
GSOC 2020- Chess Activity - Develop a new chess activity #592 and Mind-Math Activity

### PR DESCRIPTION
**Pull request by NakulTyagi**
It has the corrections offered in previous request
1. Regular replaced with king
2. Chess pieces are now clickable and movable

New Mind-Math Activity mentioned in GSOC tasks have also been added

### CODE REVIEW

**Comment by ashish0910** [comment]
Remarks : 

- There is no use of player vs player in single player mode , You need to have player vs computer ( Along with change the difficulty level ) .
- There should be an undo button
- There should be reset button 
- See rules option is not in accordance with sugar ui , please add tutorial instead ( see [here](https://github.com/llaske/sugarizer/blob/dev/docs/tutorial_step9.md) ) 
- Game should be connected to journal

**Comment by NakulTyagi** [comment]
Improvements : 
    1. Added Player vs Computer mode along with difficulty levels
    2. Added Undo and Reset Button
    3. Added tutorial and removed rules option
    4. Added journal connectivity to game

note-  undo button functionality is being added (in process)

**Comment by ashish0910** [comment]
@NakulTyagi Please do not include MindMath activity in this pull request .

**Comment by NakulTyagi** [comment]
@ashish0910  Mind Math activity has been removed.

**Comment by ashish0910** [comment]
Remarks : 

- There is scrollbar even at start of activity
- The button used in the activity are not Sugar UI friendly , they should be on toolbar 
- There is no need of showing Mathematical aspects on ui ( Positions evaluated , Time, Position/s )

**Comment by NakulTyagi** [comment]
Changes made-  
1.scrollbar removed
2.Made the buttons Sugar UI friendly, shifted to toolbar
3.Removed Mathematical aspects

**Comment by ashish0910** [comment]
The buttons used in toolbar are still not Sugar UI friendly . 

- You can use a palette for choosing difficulty modes rather than putting up separate buttons for each . 
- You can see Paint Activity for undo button .
- Journal connectivity does not work .

**Comment by NakulTyagi** [comment]
Additions-
    1.Palette added for difficulty mode.
    2. Undo button icon replaced
    3 . Journal Working
journal-working

**Comment by ashish0910** [comment]
@NakulTyagi by Journal connectivity I mean saving the current scenario of game and loading it back when run again . You can refer [here](https://github.com/llaske/sugarizer/blob/master/docs/tutorial_step4.md) for more information .

**Comment by NakulTyagi** [comment]
@ashish0910, I am facing some problems in storing the state of the chess pieces. 
Can you suggest some ways to help me with that?

**Comment by llaske** [comment]
Thanks for your proposal but it's too basic.

**Pull request closed without merging**
