### PR TITLE
MigratedMemorizeActivityToIntroJs

### PR DESCRIPTION
**Pull request by jain-arihant-2002**
Re-did the migration as last pr had some mistakes.

### CODE REVIEW

**Comment by jain-arihant-2002** [comment]
Issue #1090 is addressed in this pr.

**Comment by jain-arihant-2002** [comment]
@llaske This pr is ready to be merge. Please give feedback.

**Comment by S-kus** [comment]
Hey @jain-arihant-2002, It would be helpful if you correct the indentation of [these](https://github.com/llaske/sugarizer/pull/1176/files#diff-38811c1ddfce563537d94c68b7eaaebbf3ead4834e6ab97d933bd8c4d9c75232R9) lines similar to [this](https://github.com/llaske/sugarizer/pull/1176/files#diff-38811c1ddfce563537d94c68b7eaaebbf3ead4834e6ab97d933bd8c4d9c75232R15) one.
What's your view @llaske?

**Comment by llaske** [comment]
`jquery.min.js` is removed but still referenced.

image

**Comment by jain-arihant-2002** [comment]
> Hey @jain-arihant-2002, It would be helpful if you correct the indentation of [these](https://github.com/llaske/sugarizer/pull/1176/files#diff-38811c1ddfce563537d94c68b7eaaebbf3ead4834e6ab97d933bd8c4d9c75232R9) lines similar to [this](https://github.com/llaske/sugarizer/pull/1176/files#diff-38811c1ddfce563537d94c68b7eaaebbf3ead4834e6ab97d933bd8c4d9c75232R15) one. What's your view @llaske?

I don't why github viewing indentation wrong 
image

They look like right in my editor.

**Comment by jain-arihant-2002** [comment]
image

**Comment by jain-arihant-2002** [comment]
@llaske Can you take a look please.

**Comment by S-kus** [comment]
> I don't why github viewing indentation wrong

It's because of spaces rather than from `tabs`. 

tabs spaces

**Comment by jain-arihant-2002** [comment]
@S-kus done

**Comment by llaske** [comment]
Nice. Thanks.

**Pull request merged**
