### PR TITLE
Fixed Issue #404 & #549

### PR DESCRIPTION
**Pull request by s-mag**
Fixed Issue #404 & #549

### CODE REVIEW

**Comment by sarthak-g** [comment]
Your changes doesn't resize at all. See below:
tankdemogig

**Comment by s-mag** [comment]
Oh looks like I forgot the play mode..
Will fix it..

**Comment by s-mag** [comment]
Altered the resize function a little bit and removed the code which was causing errors.

**Comment by s-mag** [comment]
Some errors were coming when I added fullscreen buttons and called resize function.
So I altered the code a little bit.

**Pull request closed without merging**
