### PR TITLE
Update activity.js localized Planet Type

### PR DESCRIPTION
**Pull request by Shreyajags443**
Planet type was only displayed in English. Updated it to localize it.

### CODE REVIEW

**Comment by llaske** [comment]
It's a good start but you should provide localized string in the .ini file.
See [here](https://github.com/llaske/sugarizer/blob/dev/docs/tutorial/VanillaJS/step5.md) for more.

**Comment by Shreyajags443** [comment]
Hope it is good now? (hopefully the French is correct too)

**Comment by llaske** [comment]
Did you test it?
It doesn't work.

image

**Comment by Shreyajags443** [comment]
I just made another commit. I hope you are receiving my updated code. It should work

**Comment by llaske** [comment]
Same issue.
Please double check on your side before submitting a PR.

**Comment by Shreyajags443** [comment]
Hi again,

I am new to open sourcing. So as you said, I was trying to test my code. I went through the README and other docs. And to my understanding, I think I need to first install the server and then run it with that right?

If so, I am running into errors while running the Docker commands especially. The 'docker-compose up -d', etc. 
I had a few questions:
Do I run these commands on my Local terminal with the Docker App opened?
Is there anything else other than Sugarizer-server's README file?

I actually want to test my branch's code by running sugarizer but I am not fully sure how to. 
If it is through those Docker commands, I have tried them and I receive errors like this:

failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to parse stage name "llaske/multiarch-node10:": invalid reference format.

Any help is appreciated thank you

**Comment by llaske** [comment]
@Shreyajags443 you don't need to have a Sugarizer Server to test your code.
You could run Sugarizer locally in your browser.
Have a look on the section "run locally Sugarizer Application into the Web Browser" in the README.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1080

**Pull request closed without merging**
