### PR TITLE
Fixed #575 (Improvement of text palette)

### LINKED ISSUE #575: Improve design of Text Palette in Fototoon activity
The Bold and Italic buttons should get highlighted when selected so that the user knows that the text is selected bold or italics. Same can be done for the color codes. It can solved by doing minor changes in the toon.js file.

ezgif com-video-to-gif

### PR DESCRIPTION
**Pull request by sarthak-g**
fixed issue #575

### CODE REVIEW

**Comment by sarthak-g** [comment]
I encounter 2 bug in this pr.
I will commit soon after upgrading.

**Comment by llaske** [comment]
Hmmm. It look like it don't work when both Bold and Italic is selected.
See the video below:

Peek 26-01-2020 16-53

Could be related to https://github.com/llaske/sugarizer/issues/563

**Comment by sarthak-g** [comment]
Yeah, it's because of #563 
In video below, I printed whether box selected has text in italic or normal on first line and similarly bold or normal on second line.
When we come back to first page then only bold property is present.
ezgif com-video-to-gif(4)

**Comment by llaske** [comment]
Nice. Thanks.

**Pull request merged**
