### PR TITLE
Add fs button

### PR DESCRIPTION
**Pull request by est271**
- [x] closes issue #399 
- [x] The fullscreen button should be on the right of the toolbar, near the Stop button.
- [x] The fullscreen button should be always visible, including in small screen size. Could require to adapt media queries in CSS.
- [x] The size of the board should be increase in fullscreen mode. So it means that the resize event should be call directly or indirectly when clicking on fullscreen/unfullscreen button.
- [x] The unfullscreen button should be visible only when the screen is in fullscreen mode.
- [x] The unfullscreen button should be attach to the right of the screen. It's better if it's not at the same location than the Stop button to avoid side effect on multiple click.

### CODE REVIEW

**Comment by est271** [comment]
Screenshot of Fullscreen

fullscreen

**Comment by llaske** [comment]
Good job.

But you should locate the Unfullscreen button from the right size instead of using the left size (guess `right: 5%` instead of `left: 95%`).
Else the unfullscreen button could be truncated on small screens:

image

**Comment by est271** [comment]
@llaske good catch. will fix soon

**Comment by llaske** [comment]
Nice. Thanks.

**Pull request merged**
