### PR TITLE
Displaying message when MediaViewer activity is empty

### PR DESCRIPTION
**Pull request by AnandChourasia007**
Fix attempt at #1003 .
MediaViewer empty message

### CODE REVIEW

**Comment by llaske** [comment]
Sounds good but I'm surprise that the empty message is display every time.
I'm expect to have a condition to display it only if no content is read.

**Comment by AnandChourasia007** [comment]
Its working fine on my local computer. Please let me know how do I reproduce the issue.

https://user-images.githubusercontent.com/89119829/159202337-14c27a84-5136-4c6a-aa6c-d991c8a36eb0.mp4

**Comment by llaske** [comment]
Your latest commit no longer work (see error below).

image

The previous one worked but I'm expect to change visibility of the message according of the way the activity is launch.

**Comment by AnandChourasia007** [comment]
Umm, my latest commit works fine on my pc. Both when opening sugarizer in browser as well as electron. @llaske

https://user-images.githubusercontent.com/89119829/159894296-202e8883-3805-4bf5-94b0-335057fa248c.mp4

As can be seen, the message is visible only when no content is read, and when content is viewed the message is not visible.

**Comment by llaske** [comment]
I've reproduced the issue on a new environment.
Could you test again on your side?

**Comment by AnandChourasia007** [comment]
Tested again on my side, seems to work as shown in the above video though. Please wait, I will once again thoroughly try to check where this inconsistency is coming from.
Just so that we are on the same page, the problem is that on your side the code I want to get merged does not work as shown in the video, right?

**Comment by llaske** [comment]
@AnandChourasia007 Yes it doesn't work like in your video, I've got an error message in the Javascript console. So I never seen the message.
I suggest you to try to reapply your update on the latest dev branch.

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/pull/1081

**Pull request closed without merging**
