### PR TITLE
[GSOC 2020 TASK] New chess activity #592

### PR DESCRIPTION
**Pull request by sarthak-g**
My solution for #592 
- [x]  The activity should be playable against computer or against another user on the network (using presence). 
- [x]  The activity should display the list of move during play.
- [x]  The UI of the activity should be simple, self-explanatory and respect Sugar standards.
- [x]  The activity should be correctly integrated into Sugarizer and use buddy colors when possible.
- [x]  The activity should be integrated with Journal (save its context in the Journal).
- [x]  The activity should use localization.
- [x]  The activity should include a tutorial to explain the UI and an interactive tutorial to explain how each pieces move on a chessboard.
- [x]  The activity should be responsive (work on any screen size) and should include a fullscreen button.
- [x]  The activity should work on any browser (Chrome, Firefox and Safari) and in Electron.
- [x]  The activity should not depend of an Internet connection (use local content only).
- [x]  The activity should work with mouse, touch
- [x]  Every content/library used in the activity should rely on a Free Libre Open Source license.

Engine - p4wn
@llaske and @ashish0910 please review it.
Will love to know the changes you want.

### CODE REVIEW

**Comment by ashish0910** [comment]
A very good Start . May be We can highlight the possible positions on which a selected character can move .

**Comment by llaske** [comment]
Very good. The activity is pretty usable and responsive.

My remarks:

* I'm not a a big fan of the theme used for board, may be you could use the standard one instead
* It will be better to support drag&drop move
* Will be better to move to toolbar (in a palette): computer level and options
* You could use buddy color preference for background color
* Will be better to display buddy icon colors for opponent (see in Memory or LOL activity)
* Avoid color for icons in toolbar so the Switch icon should be black&white
* Player icon in toolbar could be improve: use buddy icon instead?
* Use the standard Robot icon for computer (see in Reflection activity)
* Use the standard Undo icon (see in Paint activity)
* Miss an icon to restart the game 
* Will be better to use an icon with a king instead of a pawn for the activity
* End of game popup could be improve

**Comment by sarthak-g** [comment]
> * Avoid color for icons in toolbar so the Switch icon should be black&white
@llaske , I'm not able to understand this statement.
Is it for removing black player options? or for changing color of switch button?

**Comment by llaske** [comment]
@sarthak-g it's about changing color of switch button.

**Comment by sarthak-g** [comment]
@llaske , I've made all the changes suggested by you except drag and drop move.
I've removed switch button as user can simply swap by clicking on white and black player buttons.

**Comment by ashish0910** [comment]
@sarthak-g It would be better if you could use standard instead or provide an option to switch themes . 

Also it is difficult for the user to see what possible moves a given character can move , So highlighting the possible moves will help to improve user experience in this theme .

**Comment by sarthak-g** [comment]
>@sarthak-g It would be better if you could use standard theme or provide an option to switch themes .

@ashish0910 ,you're talking about theme of background color?

 > Also it is difficult for the user to see what possible moves a given character can move , So highlighting the possible moves will help to improve user experience in this theme .

I'm working on this.

**Comment by ashish0910** [comment]
> > @sarthak-g It would be better if you could use standard theme or provide an option to switch themes .
> 
> @ashish0910 ,you're talking about theme of background color?
> 
No I mean the board theme .

**Comment by sarthak-g** [comment]
> No I mean the board theme .

This theme is standard and I've provided button for changing theme.
Which one is standard theme for you?

**Comment by ashish0910** [comment]
> > No I mean the board theme .
> 
> This theme is standard and I've provided button for changing theme.
> Which one is standard theme for you?

By theme I meant Icon design of the characters , It would be better if it was similar to [chessboard.js](https://chessboardjs.com/) . We can have @llaske advice on this .

**Comment by sarthak-g** [comment]
- Possible moves highlight
- Drag and drop functionality
- In multiplayer mode when all connected users left, host starts playing with computer from present board state.
- When host leaves then activity no more shared.
- Buddy color for background
- spectator mode(who ever connected first on network, will play with host and rest others can see)
- Opponent box developed(shows buddy icon and name of opponent)
- Practice mode(player vs player -> useful when child learn new move and want to practice it)
- Icons of chess pieces improved.
- Responsiveness increased
- Buddy icon and name displays when any user join/leave

Note: multiplayer mode may not work properly in firefox private window due to #361

**Comment by sarthak-g** [comment]
chessDisplay1
chessDisplay2

**Comment by sarthak-g** [comment]
@llaske and @ashish0910 
will love to know your feedback on changes

**Comment by ashish0910** [comment]
I am facing some issues . The game gets hanged while playing . 

error

**Comment by sarthak-g** [comment]
> 
> 
> I am facing some issues . The game gets hanged while playing .

@ashish0910  that was problem only for king. King was getting string value instead number.
I've made commit which removes this.

**Comment by ashish0910** [comment]
@sarthak-g it works now . 
One thing you can add is Check notification .

**Comment by sarthak-g** [comment]
@ashish0910 check is represented by '+' in game logs. You mean to say to popup notifications?

**Comment by ashish0910** [comment]
> @ashish0910 check is represented by '+' in game logs. You mean to say to popup notifications?

Yes , a pop up notification

**Comment by sarthak-g** [comment]
@ashish0910 added check notification with localization
checkPopup

**Comment by llaske** [comment]
Thanks for your nice implementation of the Chess activity.
It show your skill on Sugarizer activity development.
BTW we've decided that the winner of the challenge is https://github.com/llaske/sugarizer/pull/702
Feel free to propose improvements or to send PR on the activity.
Thanks again for your work.

**Pull request closed without merging**
