### PR TITLE
Fixed the error in score in FoodChain Activity

### PR DESCRIPTION
**Pull request by Vishalk91-4**
Fixes issue #1404 

Made the score to zero in FoodChain Activity, after clicking the home button once a game is finished, so that it doesn't get added up
No error in console

@llaske, could you please review it

### CODE REVIEW

**Comment by llaske** [comment]
It's a partial fix. It works when the user go back to home but it doesn't works when the user stop the activity during the game.

**Comment by Vishalk91-4** [comment]
@llaske, I mean if the user pauses during the game and plays the score shouldn't be set to reset there
Other than that, after pausing if the user clicks onto home icon, then it reset's the score

https://github.com/llaske/sugarizer/assets/116670999/d7574a0d-a1ef-4f58-bc5d-ac7b1a64208b

**Comment by llaske** [comment]
> @llaske, I mean if the user pauses during the game and plays the score shouldn't be set to reset there
> Other than that, after pausing if the user clicks onto home icon, then it reset's the score

Yes you're right but the score should be reset when the activity is close then reopen.

Ko8ZM6y65s

**Comment by llaske** [comment]
Now useless, see https://github.com/llaske/sugarizer/issues/1404#issuecomment-1811316149

**Pull request closed without merging**
