### PR TITLE
#105 Add buttons in Markdown activity to show/hide Editor/Preview

### PR DESCRIPTION
**Pull request by dinesh-sirvi**
Added buttons in toolbar
I placed the javascript code into Activity.js file.

### CODE REVIEW

**Comment by llaske** [comment]
Nice work. 
Two remarks:
- The localization is missing so the text stay in english. Please put the new titles in locale.ini and handle the localization methods for this new texts
- Slightly reduce the size of new icons.

**Comment by dinesh-sirvi** [comment]
Kindly check now..

**Comment by llaske** [comment]
Look nice but don't work. I've got a JavaScript error on Chrome:
activity.js:62 Uncaught TypeError: Cannot set property 'onclick' of null
    at activity.js:62
    at Object.execCb (require.js:1604)
    at Module.check (require.js:844)
    at Module.<anonymous> (require.js:1084)
    at require.js:129
    at require.js:1127
    at each (require.js:57)
    at Module.emit (require.js:1126)
    at Module.check (require.js:898)
    at Module.enable (require.js:1114)

**Comment by dinesh-sirvi** [comment]
I updated activity.js, used wrong name sorry for that... Everything should work fine now....

**Comment by llaske** [comment]
Don't work on Firefox: nothing happens when buttons clicked.
Could you have a look on your side ?

**Comment by dinesh-sirvi** [comment]
How can i load it on firefox? In chrome i use to do it from load unpacked extension option..

**Comment by dinesh-sirvi** [comment]
okay i just load the index.html and it worked fine. Both the buttons are working properly.Kindly check again

**Comment by dinesh-sirvi** [comment]
screenshot 48
screenshot 49

**Comment by llaske** [comment]
Sorry don't work here (see below).
No need to package it. Call it from your Sugarizer Server.

image

**Comment by llaske** [comment]
@mikklfr could you test on Firefox on your side ?

**Comment by dinesh-sirvi** [comment]
I checked it on my windows desktop with updated firefox, and it worked as expected. May be I should test it on ubuntu though i think it will make no difference. But again i added only css code that should be fully compatible with firefox atleast. I will check everything again, and will open a new pr by tomorrow... Thanks

**Comment by mikklfr** [comment]
Working as expected on firefox on Mac OS

**Comment by dinesh-sirvi** [comment]
Checked on ubuntu and is working without any issue...

**Comment by llaske** [comment]
Finally work for me too.
Merged in https://github.com/llaske/sugarizer/commit/46d467b9305bc8975d9fee2eba4037cc93f6e007

**Pull request closed without merging**
