### PR TITLE
Recommendation to Remove Redundant jQuery File from Codebase for Improved Optimization

### PR DESCRIPTION
**Pull request by VedantSharma11**
### I noticed that  "jQuery.min.js" file found in the "lib" directory does not appear to have any impact on the functionality of the following activities.
* Tanagram Activity
* EbookReader Activity
* Abacus Activity

### Since it is not being used in these activities, it is adding unnecessary bloat to the code and can be removed to reduce the file size.

### CODE REVIEW

**Comment by NischayGoyal1** [comment]
Hey @VedantSharma11 , i guess the jquery.min.js is not a bloat to the code , as by removing this file im getting this issue 
see for your reference

#### Before deleting
image


#### After
image

**Comment by VedantSharma11** [comment]
@llaske can you please review my PR

**Comment by llaske** [comment]
There is an error in ebook reader activity:

image

**Comment by VedantSharma11** [comment]
it was working fine on my side let me check it again and fix it @llaske

**Comment by VedantSharma11** [comment]
@llaske i'm not able to reproduce the console error on my side can you please tell me exactly where it is happening

**Comment by llaske** [comment]
Try to refresh your dev branch.

**Comment by VedantSharma11** [comment]
@llaske my dev branch is up to date but still i'm not able to produce it on my side, its working fine on my side

**Comment by llaske** [comment]
Nice. Thanks.

**Pull request merged**
