### PR TITLE
Replaced WebL10n with i18next in Markdown activity

### PR DESCRIPTION
**Pull request by VishnuVardhanBR**
Fixes #1378 
Locales work, no errors.

### CODE REVIEW

**Comment by llaske** [comment]
In case of fallback, the sample text is not localized.
What is it:

image

What it should be:

image

**Comment by VishnuVardhanBR** [comment]
Unable to reproduce, any specific steps?

Screenshot

**Comment by llaske** [comment]
> Unable to reproduce, any specific steps?

Hmmm. Guess you're running Sugarizer App locally (using Electron or file:///), I've tested on a local Sugarizer server.
It can make a difference because there is a delay loading files.

**Comment by VishnuVardhanBR** [comment]
I'm unable to reproduce on the server. I tried throttling the cpu and network using devtools, but couldn't see the issue, is there any another way?

Screenshot 2024-02-20 at 1 22 34 AM

**Comment by VishnuVardhanBR** [comment]
> I guess the problem is that [this line](https://github.com/llaske/sugarizer/blob/dev/activities/Markdown.activity/js/activity.js#L12) could be executed before locale initialization. 

Most likely. I can fix it but I just can't reproduce it to test before committing, please take a look below.

https://github.com/llaske/sugarizer/assets/64434937/4572747b-7462-42fb-8807-b00d4c007143

**Comment by llaske** [comment]
Strange. It happens each time on my side.

wE9tB0e4a7

**Comment by VishnuVardhanBR** [comment]
I made some changes but i'm unable to validate whether it works or not, what do I do?

**Comment by Vishalk91-4** [comment]
@llaske 

I tried in my system as well, it's showing the same thing, perhaps a localization issue
Screenshot 2024-02-25 183233

**Comment by soham2312** [comment]
@llaske please review the Indentation changes

**Pull request closed without merging**
