### PR TITLE
Exerciser Activity: Add title to buttons on Exercise cards.

### PR DESCRIPTION
**Pull request by akshat157**
Adds an "explanation" to the three buttons - Play, Edit, Delete buttons on the homepage of Exerciser Activity.
Felt the need for it myself when ran the activity first time.

### CODE REVIEW

**Comment by ashish0910** [comment]
@akshat157 can you please remove `package-lock.json` and `package.json` files from the PR .

**Comment by akshat157** [comment]
Surely. I was thinking the same.
Thanks for clearing up on the `package-lock.json`, `package.json` files confusion.

**Comment by akshat157** [comment]
@ashish0910 Do I need to make the index.html for Exerciser obfuscated as well (a one liner) as it previously was?

**Comment by llaske** [comment]
For Exerciser activity, please fill issues directly on the [Exerciser repository](https://github.com/llaske/ExerciserReact/) because the code here is generated.
BTW this issue is already fixed in this PR: https://github.com/llaske/ExerciserReact/pull/12

**Comment by akshat157** [comment]
Oh! Thanks for this one. Didn't know. I'll close the PR now as it is fixed already.

**Pull request closed without merging**
