### PR TITLE
Rewrite Chat activity in Vue.

### PR DESCRIPTION
**Pull request by UtkarshSiddhpura**
The new UI of the Chat activity is shown here #1356
I've done some changes in UI (open for feedback).

### CODE REVIEW

**Comment by llaske** [comment]
Very cool :+1: 

Few suggestions:

* [ ] When several users are typing their name are mixed
* [ ] I think the typing detection could be simplified: an user is typing while there is some text in its input

ziJEzXTj5q

* [ ] When the user is not connected, the input box should be grayed/disabled with a message inside suggesting to user to share the activity. It's specially important when the activity is reopen from the Journal

**Comment by llaske** [comment]
Nice !
My remarks:

* [ ] Doesn't support multiple typing. Only one user is mentioned

Capture d’écran du 2023-09-16 10-58-19

* [ ] Typing mention disappears when you have the focus on the typing area or if you start typing

V9bVd98mYw

* [ ] It will be nice to add a clear button in the toolbar to clean the history (use the "standard" clean icon from other activities)

**Comment by llaske** [comment]
Thanks @UtkarshSiddhpura . I think it's almost ready to release.
Some remarks:

* [ ] There is a vuejs warning

image

* [ ] It seems that localization doesn't work

image

**Comment by UtkarshSiddhpura** [comment]
>     * [ ]  There is a vuejs warning

I don't see any warning can you please check again.

**Comment by llaske** [comment]
Few remarks:

* [ ] Seems that the UserJoin / UserLeft localization strings are missing. I guess it's now here because you've reintegrated humane popup. May be this notification is useless - except in the case below - since there is an explicit message in the conversation.

Capture d’écran du 2023-10-18 22-01-24

* [ ] When an user left and the user is reading previous messages, the popup "New message from X" is displayed. This popup is not pertinent.

Capture d’écran du 2023-10-18 22-03-45

**Comment by llaske** [comment]
Nice. Thanks.

**Pull request merged**
