### PR TITLE
Fixes #604(Responsiveness of stopwatch activity)

### LINKED ISSUE #604: Stop Watch Activity is not responsive and has text overflowing problem.
stop watch activity has text overflowing problem.

Screenshot from 2020-02-13 19-20-17

the activity is not responsive also. so user will face problem on small screens.

Screenshot from 2020-02-13 19-20-25
Screenshot from 2020-02-13 19-21-00

### PR DESCRIPTION
**Pull request by superhakar**

### CODE REVIEW

**Comment by superhakar** [comment]
Big-screen
Meduim-screen
Mobile-screen
potrait-tablet-screen
Tablet-screen

**Comment by llaske** [comment]
Good job. It works very well.

BTW I'm worried about your use of Bootstrap version 4.
Another issue on this activity (https://github.com/llaske/sugarizer/issues/596) is to add a tutorial and it will require using Bootstrap tour (see [here](https://github.com/llaske/sugarizer/blob/dev/docs/tutorial_step9.md#integrate-bootstrap-tour-components)) but Bootstrap tour is not compatible with Bootstrap version 4.

Do you have a way to do the same with Bootstrap version 3?

**Comment by superhakar** [comment]
Bootstrap’s(version 4) "cards" make it simple to work in this case. I can recreate this cards in activity.css and the rest of it will work with Bootstrap version 3.

**Comment by llaske** [comment]
Please fix conflict related in PR

**Comment by superhakar** [comment]
Fixed conflict. Please review.

**Comment by llaske** [comment]
Good job. Thanks.

**Pull request merged**
