### PR TITLE
Fixed, ctrl + a and ctrl + backspace functionalities

### PR DESCRIPTION
**Pull request by Vishalk91-4**
Fixes issue #1515 

https://github.com/llaske/sugarizer/assets/116670999/388c97d8-6e2d-4268-b4e5-4d1fdf2def1d
@llaske could you please review this PR, I haven't fixed things for long pressing

### CODE REVIEW

**Comment by llaske** [comment]
It's a partial fix, following is a Ctrl+A following by Del

KWlIC47P77

**Comment by UtkarshSiddhpura** [comment]
I think rather handling every actions of user, we could go for more minimal effort just like it's in v1
That's why i raised another PR #1527

**Comment by llaske** [comment]
Good idea @UtkarshSiddhpura.
BTW the Ctrl +a and Ctrl + backspace has to be fixed.

**Comment by UtkarshSiddhpura** [comment]
> BTW the Ctrl +a and Ctrl + backspace has to be fixed.

Isn't my PR fixes it or we want some modified behavior than v1?

**Comment by llaske** [comment]
> Isn't my PR fixes it or we want some modified behavior than v1?

@UtkarshSiddhpura  We could add the handling of CTRL+A and CTRL+Backspace that was not handled in v1
@Vishalk91-4 I'm not sure to understand the commit https://github.com/llaske/sugarizer/pull/1519/commits/4a9e84c04a63c3a810538a05d75c72df6edff04e

**Comment by Vishalk91-4** [comment]
> > Isn't my PR fixes it or we want some modified behavior than v1?
> 
> @UtkarshSiddhpura We could add the handling of CTRL+A and CTRL+Backspace that was not handled in v1 @Vishalk91-4 I'm not sure to understand the commit [4a9e84c](https://github.com/llaske/sugarizer/commit/4a9e84c04a63c3a810538a05d75c72df6edff04e)

@llaske, that commit `4a9e84c` was due to conflicting files, fter some updation in password.js

**Comment by Vishalk91-4** [comment]
@llaske 
Now, I have correctly added the ctrl + a and backspace, selection of text at any point in password and pressing any key replaces the selected one with that key, or backspace removes the selected part

Could you please review it now

**Comment by llaske** [comment]
That's nice @Vishalk91-4 , it fix the issue.
There is still an issue, it's possible to type illegal characters (i.e. characters not matching an emoji)

N767ALGOLb

**Comment by Vishalk91-4** [comment]
@llaske
I have fixed those non mapping characters, also I mistakenly added just A to function as ctrl + , changed it to ctrl + A

**Comment by llaske** [comment]
Nice @Vishalk91-4 . Thanks.

**Pull request merged**
