### PR TITLE
Replaced Bootstrap Tour By IntroJS in Curriculum Activity 

### PR DESCRIPTION
**Pull request by prakharSrivs**
#1090 
Replace Bootstrap Tour By IntroJS in Curriculum Activity

### CODE REVIEW

**Comment by Ayeshashaik759** [comment]
@prakharSrivs just a small suggestion from my side I think you have not made changes in css/activity.css file hope you check it once.

**Comment by prakharSrivs** [comment]
Thank you for reviewing it @Ayeshashaik759 
I'll be shortly pushing an update to the branch

**Comment by llaske** [comment]
It does not work: nothing happens and there is an error in the console.

image

**Comment by llaske** [comment]
@Ayeshashaik759 are you still working on it?

**Comment by prakharSrivs** [comment]
Hi @llaske  , Actually my midterms were going on so I was not able to work on it.
But I will surely look into it now.

**Comment by llaske** [comment]
Closed due to lack of activity

**Pull request closed without merging**
