### PR TITLE
unable to play the recorded video in the record activilty

### PR DESCRIPTION
**Pull request by yashveeeeer**
fixing issue #1203  and #1661

### CODE REVIEW

**Comment by yashveeeeer** [comment]
@llaske would you please review it.

**Comment by llaske** [comment]
Smart fix. Thanks.
Did you had opportunity on others operating system than Windows? 
As you know, Sugarizer is multi-platform so the fix should work on every platform.
I've read that VP8 has broader compatibility, especially in older devices and software. May be it could be better to use VP8 than VP9.

**Comment by yashveeeeer** [comment]
Thanks @llaske, Yeah I will try to see the fix on different OS using Virtual Machine.
and  you are right about VP8 has broader compatibility on older devices than VP9, I just read that , I will change it to that after checking the fix on different OS.

**Comment by yashveeeeer** [comment]
kindly ignore that force push and i have changed VP9 to VP8, I have also check the fix on Linux.
actually the video player is working fine in Linux, the problem is only with the windows environment, when I added the fix the video was still working fine with Linux.

**Comment by llaske** [comment]
Thanks a lot for fixing this very old bug.

**Comment by yashveeeeer** [comment]
My pleasure, I learned a lot, from this bug.

**Pull request merged**
