### PR TITLE
Added tutorial in Grid Paint Activity.

### PR DESCRIPTION
**Pull request by s-mag**

### CODE REVIEW

**Comment by llaske** [comment]
It don't work. The screen become gray but the popup doesn't appears.

**Comment by s-mag** [comment]
> It don't work. The screen become gray but the popup doesn't appears.

This is the problem emerging with me ... I did all the steps correctly but I am not getting why the popups doesn’t appear... They work if we click right arrow from the keyboard but the css is not showing up... I don’t know why... Can you suggest me a way to solve this issue...

**Comment by llaske** [comment]
Not sure it's related but webL10n is not initialized in this activity.

**Comment by s-mag** [comment]
> Not sure it's related but webL10n is not initialized in this activity.

Its not related to wbL10n.....

**Comment by llaske** [comment]
It's related to webL10n, when I'm removing all call to `l10n.get` method in your file, the popup is displayed...

**Comment by s-mag** [comment]
> It's related to webL10n, when I'm removing all call to `l10n.get` method in your file, the popup is displayed...

Oh yes.. Thanks. I will do the necessary changes now..

**Comment by s-mag** [comment]
Added Popups and fixed the Issue.
Thanks.

**Comment by llaske** [comment]
You must not hard code the text for the tutorial, you should make localization work!

**Comment by sdziuda** [comment]
I've also encountered the problem with localization not being initialized at all. Anyway fixing it is really simple. You need to go back to [step 5 of the tutorial](https://github.com/llaske/sugarizer/blob/dev/docs/tutorial_step5.md) and add some code in activity.js and index.html
I hope I could help you a little :)

**Comment by s-mag** [comment]
> I've also encountered the problem with localization not being initialized at all. Anyway fixing it is really simple. You need to go back to [step 5 of the tutorial](https://github.com/llaske/sugarizer/blob/dev/docs/tutorial_step5.md) and add some code in activity.js and index.html
> I hope I could help you a little :)

Thanks man...

**Comment by s-mag** [comment]
> You must not hard code the text for the tutorial, you should make localization work!

Ok sir I will add localization

**Comment by s-mag** [comment]
Added Localization but i have not translated for other languages..

**Comment by llaske** [comment]
It's better.

Two remarks:

- The webL10n is not initialized so the tutorial language is always the language of the browser. You should initialized by using code mentioned [here](https://github.com/llaske/sugarizer/blob/dev/docs/tutorial_step5.md#initialize-localization).
- Will be nice to display a different tutorial in list mode and in detailed mode. You could differentiate it using the global variable `mode`. See [here](https://github.com/llaske/sugarizer/blob/dev/activities/Gridpaint.activity/js/gridpaint.js#L55).

**Comment by s-mag** [comment]
> It's better.
> 
> Two remarks:
> 
> * The webL10n is not initialized so the tutorial language is always the language of the browser. You should initialized by using code mentioned [here](https://github.com/llaske/sugarizer/blob/dev/docs/tutorial_step5.md#initialize-localization).
> * Will be nice to display a different tutorial in list mode and in detailed mode. You could differentiate it using the global variable `mode`. See [here](https://github.com/llaske/sugarizer/blob/dev/activities/Gridpaint.activity/js/gridpaint.js#L55).

I will do the changes right away..

**Comment by s-mag** [comment]
Added different tutorial for different modes and fixed Localization.

**Comment by llaske** [comment]
Nice.

One more issue, a horizontal scrollbar appears when the tutorial is launched:

image

**Comment by s-mag** [comment]
Changed Placement.. to center

**Comment by s-mag** [comment]
@llaske Is this approach fine.

**Pull request merged**
