### PR TITLE
Abacus does not display solution with big numbers #140 

### LINKED ISSUE #140: Abacus does not display solution
The sbacus does not display the solution if the numbers get too big. 
image
The solution gets cut off at the end. This problem could be resolved by displaying the solution on the side of the abacus.

### PR DESCRIPTION
**Pull request by FreddieN**
Fixes #140 
The text now dynamically changes size according to the available canvas space and the length of the sum. I thought this solution was best.
Example:
demo

Let me know if you want me to try another solution.

### CODE REVIEW

**Comment by llaske** [comment]
Very good. The size decrease when no enough room left but it will be better if the size increase when space left increase. The text should try to have the best possible size.

**Comment by FreddieN** [comment]
@llaske Could you send a screenshot so I can understand what you mean?

**Comment by llaske** [comment]
Here is a screen capture: at end we could expect that the size should be larger.

pr240_issue

**Comment by FreddieN** [comment]
This issue should now be fixed.

**Comment by llaske** [comment]
Very good. Congratulation.

**Pull request merged**
