### PR TITLE
Required Buttons have been properly fitted and their UI is slightly changed

### PR DESCRIPTION
**Pull request by Vishalk91-4**
Fixes issue #1124 

Hi @llaske
The Extra Spaces have now been removed and the Code works properly.

You commented whether this work on other Languages or not
So, I've tested it for French and all those which were mentioned in the Language section it supports them, the box doesn't run out of space .

Page View After Modification
image
image
image

In French
image

### CODE REVIEW

**Comment by Vishalk91-4** [comment]
@llaske could you please review it

**Comment by llaske** [comment]
There are width issues in French and in Spanish on text and on icons in tutorial.

image

image

image

Plus I'm not sure just reducing width will be enough. The idea will be to adapt button size depending of the text.

**Comment by Vishalk91-4** [comment]
@llaske Yes I thought of that at first just forgot midway, 

I have changed them so that it can adapt according to the text, You can look at them here
Just, one thing I wanted to know whether you want to change the word back to previous, since the translation you showed was of Previous and all of them had Back there.

Screenshot 2023-05-26 074418
Screenshot 2023-05-26 074448
Screenshot 2023-05-26 082112

@llaske should I make the changes in this form.

**Comment by Vishalk91-4** [comment]
@llaske I've added a commit which should possibly fix this issue, could you please review it

**Comment by llaske** [comment]
That's nice. Thanks.

**Pull request merged**
