### PR TITLE
Replaced Bootstrap tour by IntroJs in Reflection Activity 

### PR DESCRIPTION
**Pull request by ABHINAV-JHA-27**
Migrated Reflection activity from Bootstrap Tour to IntroJs https://github.com/llaske/sugarizer/issues/1090

### CODE REVIEW

**Comment by ABHINAV-JHA-27** [comment]
Hi @llaske , I have migrated Reflection Activity. Can you Please review ?

**Comment by llaske** [comment]
There is an issue, scrollbars appears on the board popup

image

**Comment by ABHINAV-JHA-27** [comment]
My bad will look into it

**Comment by ABHINAV-JHA-27** [comment]
Hi @llaske , I fixed the issue. Can you have a look.

**Comment by llaske** [comment]
Nice. Thanks.

**Pull request merged**
