### PR TITLE
Replaced Bootstrap tour by IntroJs in Chess activity

### PR DESCRIPTION
**Pull request by saakxshi**
I have migrated Chess activity tutorial from bootstrap-tour to IntroJs
Issue: https://github.com/llaske/sugarizer/issues/1090

[screen-capture.webm](https://user-images.githubusercontent.com/91880528/213904578-512cdcaa-8556-497f-a00f-14dfd7642e7e.webm)

### CODE REVIEW

**Comment by llaske** [comment]
Thanks for your contribution but SPACE//TAB should not be change in original files.

**Comment by saakxshi** [comment]
@llaske please check and let me know if any changes are to be made.

**Comment by llaske** [comment]
Icons are no longer displayed in the tutorial.

image

See in other activities (for example GameOfLife) how to keep this feature.

**Comment by saakxshi** [comment]
Sure i'll look into it.

**Comment by Ayeshashaik759** [comment]
Hlo @saakxshi you can solve this issue by making the following changes in the tutorial.js file and you can even remove the showPieces (from line 66 to 90) method in tutorial.js after this.

Screenshot (118)

The output view.
Screenshot (119)

**Comment by saakxshi** [comment]
@Ayeshashaik759 Thanks for your input.
@llaske Now the icons are visible, but there's one issue regarding the closebutton position in the pawn title. In order to solve this issue, I looked into PR #1099 and #1096, which suggested downgrading the introjs version, but even after doing that, there was no change, so can you suggest what is needed to be done?

image

**Comment by Ayeshashaik759** [comment]
@saakxshi this is not an issue it is a normal case when the text length is more.

**Comment by saakxshi** [comment]
> @saakxshi this is not an issue it is a normal case when the text length is more.

How it can be fixed?

**Comment by Ayeshashaik759** [comment]
> > @saakxshi this is not an issue it is a normal case when the text length is more.
> 
> How it can be fixed?

No need to fix it actually 😅

**Comment by llaske** [comment]
Nice. Thanks for your work @saakxshi

**Pull request merged**
