### PR TITLE
Chess Activity (GSoC 2020)

### LINKED ISSUE #592: Develop a new chess activity
> This issue is a challenge for students to the [GSoC 2020](https://github.com/sugarlabs/GSoC/blob/master/Ideas-2020.md). Every student interested to be candidate to GSoC 2020 Sugarizer projects must complete this task.

Develop **a new chess activity** for Sugarizer.

image

Detailed features expected:
- [ ] The activity should be playable against computer or against another user on the network (using presence).
- [ ] The activity should display the list of move during play.
- [ ] The UI of the activity should be simple, self-explanatory and respect Sugar standards.
- [ ] The activity should be correctly integrated into Sugarizer and use buddy colors when possible.
- [ ] The activity should be integrated with Journal (save its context in the Journal).
- [ ] The activity should use localization.
- [ ] The activity should include a tutorial to explain the UI and an interactive tutorial to explain how each pieces move on a chessboard.
- [ ] The activity should be responsive (work on any screen size) and should include a fullscreen button.
- [ ] The activity should work on any browser (Chrome, Firefox and Safari) and in Electron.
- [ ] The activity should not depend of an Internet connection (use local content only).
- [ ] The activity should work with mouse, touch and possibly keyboard.
- [ ] Every content/library used in the activity should rely on a Free Libre Open Source license.

Technically speaking, the activity could be written using pure JavaScript or using Vue.js inline (as in the [Calligra activity](https://github.com/llaske/sugarizer/tree/dev/activities/Calligra.activity)). JavaScript ES6 syntax should be avoided.

The activity should be based on [Chessboard JS](https://chessboardjs.com/) for the UI  and  [P4wn](https://github.com/douglasbagnall/p4wn) for the engine.

### PR DESCRIPTION
**Pull request by utkarsh-raj**
Fixes #592 
Initial submission for the task. Would request @llaske and @ashish0910 , and other members to kindly review. The features include:
- Playable with other users (using the Presence Framework).
- Displays the list of moves during play.
- Uses buddy colors for the background, move history and the XO Icons for users.
- Integrated with Journal.
- Implements Localization with the web10Ln Library.
- Includes a tutorial with written instructions on how to move each of the pieces on the board.
- Is responsive with Bootstrap 3 and includes a Fullscreen button. 
- Tested to work on Google Chrome, Mozilla Firefox and Electron.
- Does not depend on the internet.
- Gives information about Check, Checkmate, Draw and Stalemate in the More Information section.
- The Spectators area comes alive when 2+ players join, or if one leaves the network.
- If more than 2 players join the same game on the network, the third player and onwards become the spectators, and Buddy Color Icons are used to notify everyone.
- If the any of the player leaves, all the players are notified in the spectators area.
- Implements two levels of computer difficulty (Random and Gains based algorithms) in the current version.
- Provides Undo and Restart options in the Single Player mode.

The activity is built utilising [Chessboard.js](https://chessboardjs.com/) for the Chess layout and [Chess.js](https://github.com/jhlywa/chess.js) for moves validation. The engine is self written (inspired by the [Lauri Hartikka](https://www.freecodecamp.org/news/simple-chess-ai-step-by-step-1d55a9266977/)) and the Sugar Web Library is for the UI.

Further work (would love to have community feedback on how to improve well here):
- Better Leave Network implementation.
- Switching sides. (Updated in 58cd959)
- Less dependence on text and focus on colors.
- Better UI design.
- Interaction in the tutorial by the player. 
- More complex AI algorithms. (Updated in 2838724)

Screenshot at 2020-03-15 01-01-28
single-player-check

### CODE REVIEW

**Comment by ashish0910** [comment]
Good start . I Found UI very colourful and good . 
Few remarks : 
- I have issues with difficulty level . The hard does not really work like hard mode . It works as if easy mode . Also there should be more than 2 difficulty modes . 
- Option to switch between white and black will be appreciated .

**Comment by utkarsh-raj** [comment]
You are correct @ashish0910 , seems like the method was relatively easy. Made it Medium and added new difficulty level Hard, and can be accessed by the same toolbar buttons. Implements the Graph Searching, so might take some time in calculations.
Also added switch sides button. Thanks for the review!

**Comment by ashish0910** [comment]
The new hard mode is good but slow . May be you can use [p4wn](https://github.com/douglasbagnall/p4wn) or some other way to improve it .

**Comment by utkarsh-raj** [comment]
Another approach might be to give the user an option to set the depth of the search in the Graph Algorithm, which is currently preset to 3. An increased depth will make the computer play better, but slower, and vice versa.
Let me know your thoughts @ashish0910 , I will work on the p4wn.js integration in the meanwhile.

**Comment by ashish0910** [comment]
No @utkarsh-raj I don't think adding depth option is a good idea . It will make things complicated for students .

**Comment by utkarsh-raj** [comment]
Okay @ashish0910 , you're right. The complexity of the UI is a major point. I will just go ahead with the p4wn.js Engine.

**Comment by llaske** [comment]
Thanks for your nice implementation of the Chess activity.
It show your skill on Sugarizer activity development.
BTW we've decided that the winner of the challenge is https://github.com/llaske/sugarizer/pull/702
Feel free to propose improvements or to send PR on the activity.
Thanks again for your work.

**Pull request closed without merging**
