### PR TITLE
 Show message when there is no activity matching the search (listview)  #1561 

### PR DESCRIPTION
**Pull request by hharshas**
@llaske #1561 [TODO.md](https://github.com/llaske/sugarizer/blob/feature/v2/v2/TODO.md)

### CODE REVIEW

**Comment by llaske** [comment]
It's nice but the icon and the message appears during 1 second before loading the activity.
Would be nice to avoid it.

By1rJlW7er

**Comment by hharshas** [comment]
@llaske review the changes.

**Comment by llaske** [comment]
That's nice but because Sugarizer is use by children and some of them can't read, it's always better to avoid text.
I suggest to replace it by the `spinner-light.gif` already in the repo.

**Comment by hharshas** [comment]
@llaske  there is no image folder in v2, so I've called the gif from outside, but there should be one isn't it ?

**Comment by llaske** [comment]
Yes

**Comment by hharshas** [comment]
@llaske 
so can I copy one to v2 ?

**Comment by llaske** [comment]
Yes copy it instead of referencing the original, the v1 directory is supposed to be removed at end

**Comment by hharshas** [comment]
@llaske You can check the changes now.

**Comment by llaske** [comment]
Nice but please add only the `spinner-light.gif` from now

**Comment by hharshas** [comment]
@llaske  yeah adding other assets will be make it messy for now !!!!

**Comment by llaske** [comment]
Good job. Thanks.

**Pull request merged**
