### PR TITLE
#Issue 594 Add Chat Tutorial, fixed issue with previous PR #641

### PR DESCRIPTION
**Pull request by Hemansh31**
Fixed issue with previous #641 , thanks to @s-mag for pointing out. @s-mag @llaske please do review

### CODE REVIEW

**Comment by s-mag** [comment]
@Hemansh31 You should not make changes that are not required.. you made the changes in activity.js that were not required...

**Comment by Hemansh31** [comment]
@llaske please review..

**Comment by Hemansh31** [comment]
@llaske ???

**Comment by llaske** [comment]
Nice job. Thanks.

**Pull request merged**
