### PR TITLE
Replaced Bootstrap tour by IntroJs in Food Chain activity #1090

### PR DESCRIPTION
**Pull request by ABHINAV-JHA-27**
Migrated Food Chain activity from Bootstrap Tour to IntroJs
https://github.com/llaske/sugarizer/issues/1090

### CODE REVIEW

**Comment by llaske** [comment]
Look like visibility of buttons is not handle. The popup should not be displayed when the button is not visible.

image

**Comment by ABHINAV-JHA-27** [comment]
@llaske can you please elaborate a bit. I mean which button.

**Comment by llaske** [comment]
My screen capture show the popup for the button to go back to home screen but this button is visible only when the game is paused. When the button is invisible, the popup should not be visible. Have a look on the original tutorial to understand the behavior.
Your issue is related to filter steps condition, you could find others PR which fixed the issue.

**Comment by ABHINAV-JHA-27** [comment]
Hey @llaske , as you said i have checked my filtering condition but i could not find any errors. Also I made sure to look it up in other PRs and they too have this similar statement for filtering.

`steps = steps.filter((step) => 
        !("element" in step) ||
        (step.element.length &&
          document.querySelector(step.element) &&
          document.querySelector(step.element).style.display != "none")
);`

**Comment by ABHINAV-JHA-27** [comment]
Hey @llaske , I did find the mistake and have corrected it. can you please review

**Comment by llaske** [comment]
Nice @ABHINAV-JHA-27 .
There is another issue: scrollbars appears on the board game popup.

image

**Comment by ABHINAV-JHA-27** [comment]
@llaske  fixed it

**Pull request merged**
