### PR TITLE
Feature/minesweeper activity

### PR DESCRIPTION
**Pull request by kunal-mohta**
screenshot from 2017-12-28 01-28-17
screenshot from 2017-12-28 01-32-32
screenshot from 2017-12-28 01-33-00
screenshot from 2017-12-28 01-32-42

### CODE REVIEW

**Comment by llaske** [comment]
Nice.
BTW some improvements are need:
- The icon should be more Sugarized: use two colors and integrate user color - see [here](https://github.com/llaske/sugarizer/blob/dev/docs/tutorial_step2.md) for more
- Level buttons should be in the toolbar - see LOL activity for example
- Scrollbar appears on the window
- Should be nice to have opportunity to choose size - see Memory activity for example
- Cells are too small, the game will be unusable on touch
- Datastore should be handle to save unfinished game - see [here](https://github.com/llaske/sugarizer/blob/dev/docs/tutorial_step4.md) for more

**Comment by kunal-mohta** [comment]
I don't understand what do you mean by scrollbar appearing on window.

**Comment by kunal-mohta** [comment]
- [x] Icon sugarized
- [x] Level buttons in toolbar
- [ ] Scrollbar appears on window 
- [x] Choice of size
- [x] Cell size increased
- [x] Data storage for unfinished games

screenshot from 2018-01-08 10-53-09
screenshot from 2018-01-08 10-53-15
screenshot from 2018-01-08 10-53-20

**Comment by llaske** [comment]
Look better now.
- Still have issue on scrollbar (see below)

image

- Icons could be enhanced: see Memorize activity for size icons and LOL activity for difficulty.
Activity icon is too big. Could you reduce its size?
- I think that the smiley face is a lost of space. May be you could put it to the left of board or completely remove it.
- Could be nice if color of numbers change (like in the original Windows game).
- Could be nice if an empty cell is white (too many gray here).

Please send PR only to dev branch (you've sent this one to master branch)

**Comment by kunal-mohta** [comment]
I am sorry that I sent the PR to `master` branch.
I have changed it to `dev` right now.
I will look upon your suggestions and try to implement them as soon as possible.

**Comment by kunal-mohta** [comment]
- [x]  Empty cell is white
- [x]  Color of number changed
- [x]  Smiley removed
- [ ]  Change Icons
- [ ]  Scrollbar

**Comment by kunal-mohta** [comment]
*Memorize* had a consistent size of `4x4, 5x5, 6x6`, however *Minesweeper* has possible sizes as `13x15, 13x20, 13x25` which makes it difficult to have size icons similar to that in *Memorize*. 
Consider the following mock design - 
mock

**Comment by llaske** [comment]
Finally not pertinent to include in Sugarizer.

**Pull request closed without merging**
