### PR TITLE
FIXED -> Vertical bar are broken in Chart/Gears activities on Windows 

### LINKED ISSUE #1646: Vertical bar are broken in Chart/Gears activities on Windows
On Chrome Window, the vertical bar used in activities toolbar to split group of icons is broken.

It look like:

image

and should be:

image

Issue is both on Chart and Gears activity

### PR DESCRIPTION
**Pull request by MdSaifAliMolla**
Fix  #1646

### CODE REVIEW

**Comment by llaske** [comment]
The fix totally broke the UI on other platforms.

image

Because Sugarizer works on any platform, any fix should preserve the compatibility with every supported platform.

**Comment by MdSaifAliMolla** [comment]
@llaske Sorry to bother  but which platform is it and how can I test if my pr is compatible with other platforms.
I have checked responsiveness using devtools and it worked fine.

**Comment by MdSaifAliMolla** [comment]
@llaske  Updated the pull request. I think the problem should be solved now .

**Comment by llaske** [comment]
> @llaske Updated the pull request. I think the problem should be solved now .

it's not.

image

did you try on your side?

**Pull request closed without merging**
