### PR TITLE
Replaced bootstrap-tour with introJs tour library in calculate Activity

### PR DESCRIPTION
**Pull request by Ayeshashaik759**
I have migrated calculate activity tutorial from bootstrap-tour to IntroJs
Issue: https://github.com/llaske/sugarizer/issues/1090

### CODE REVIEW

**Comment by llaske** [comment]
The title bar has not the right color.

image
image

**Comment by Ayeshashaik759** [comment]
hlo @llaske I made the changes you mentioned please review it once


Screenshot (48)

**Comment by llaske** [comment]
That's better for the title color but there is now a non expected horizontal line between text and buttons.
Try to retrieve the same styles than in others activities migrated to IntroJS.

image

**Comment by Ayeshashaik759** [comment]
Actually I retrieved the same styles as in other activities migrated to introJS but still got this changes in styles. Now I repeated the same process as you said hope it is works correctly this time.

Screenshot (50)

**Comment by llaske** [comment]
Nice. Thanks.

**Pull request merged**
