### PR TITLE
Add an history of last QR Code generated/read in QR Code activity 

### LINKED ISSUE #244: Add an history of last QR Code generated/read in QR Code activity
Add an history of QR Code generated (or read). So the user could retrieve its history when he reopen the activity. The history could be represented by a sort of ComboBox in the input field.
The history should be stored in the datastore. See https://github.com/llaske/sugarizer/blob/dev/docs/tutorial_step4.md for more.
The source of the QR Code activity is located here: https://github.com/llaske/sugarizer/tree/dev/activities/QRCode.activity

### PR DESCRIPTION
**Pull request by FreddieN**
Fixes #244
This PR implements the functionality to restore previously generated barcodes. See below:
Choose QR's with dropdown:
demo
QR's being saved to datastore:
demo

### CODE REVIEW

**Comment by llaske** [comment]
That's the idea but I'm not a big fan to add a new line for the combo. It take lot of space.
I suggest to use and hidden combo, like in https://github.com/llaske/sugarizer/pull/241

**Comment by FreddieN** [comment]
Is this any better?
demo

**Comment by FreddieN** [comment]
I've added these changes.
demo

**Comment by llaske** [comment]
Works very well. Thanks.

**Pull request merged**
