### PR TITLE
Resolved issue #903 (Seperate functionality of hours and minutes)

### PR DESCRIPTION
**Pull request by sarthak-g**
As discussed in #903 

- [x] Seperate functionality for hours and minutes
- [x] Reduced clock radius when displaying minutes so that minutes do not go out of board 

https://user-images.githubusercontent.com/42293606/103177053-e17b8a00-489c-11eb-9140-16f2489c911a.mp4

### CODE REVIEW

**Comment by llaske** [comment]
That's the idea but in 24h mode the digits 13h to 23h should appear like before (with a smaller font), it should not replace the 1h to 12h digits. 

image

**Comment by sarthak-g** [comment]
@llaske, changed font size according to hour format.

**Comment by llaske** [comment]
Sorry I was not clear. It's not what I expected.
The 12/24 button should just add the inner circle with 13-23h, not replace the outer circle with 1-12h.
Like it was in your first PR:

image

**Comment by sarthak-g** [comment]
@llaske made suggested changes

**Comment by llaske** [comment]
Perfect. Thanks a lot.

**Pull request merged**
