### PR TITLE
modified erase button

### LINKED ISSUE #700: Text not showing under erase button in qr-code activity
Erase button in the input area is hiding some text under it.
Screenshot from 2020-03-14 00-38-49

### PR DESCRIPTION
**Pull request by Swayamsvk**
fixed #700

### CODE REVIEW

**Comment by Swayamsvk** [comment]
Screenshot from 2020-03-14 00-51-14

**Comment by llaske** [comment]
Your fix just put the erase button outside input field. The erase button should stay in the input field. See how it works on the Sugarizer home view search field.

**Comment by Swayamsvk** [comment]
@llaske I have made the necessary changes please review them.

**Comment by Swayamsvk** [comment]
qr1

**Comment by Swayamsvk** [comment]
qr2

**Comment by Swayamsvk** [comment]
@llaske can you please review this PR I think I have made the changes as requested tell me if anything else is required.

**Comment by llaske** [comment]
Look better but the Place holder text should be localized

**Comment by Swayamsvk** [comment]
@llaske added localization please review this and if possible merge this.

**Comment by llaske** [comment]
Nice but something is wrong. In Sugarizer, the background is supposed to be white when the field is focused (see for example how it works in the Sugarizer Home view search field)

**Comment by Swayamsvk** [comment]
speak3

**Comment by Swayamsvk** [comment]
@llaske I have made the changes as you have requested please review this.

**Comment by llaske** [comment]
Nice.

Could you improve vertical alignment for buttons. Both cancel and right arrow buttons should be vertically centered.

image

**Comment by Swayamsvk** [comment]
Screenshot from 2020-03-28 16-54-26

**Comment by Swayamsvk** [comment]
@llaske I have fixed this issue please merge this.

**Comment by llaske** [comment]
Nice. Thanks.

**Pull request merged**
