### PR TITLE
Replaced webL10n to i18next in TankOp

### PR DESCRIPTION
**Pull request by Vishalk91-4**
Migrated Tank Operation to i18next
image

@llaske, could you please review this PR

### CODE REVIEW

**Comment by Rohan20-10** [comment]
@Vishalk91-4 could u pls help me out with this problem.
while creating pull request I am getting changes in all 869 files.
pls click on the following [link](https://github.com/llaske/sugarizer/issues/1378#issuecomment-1884176490) to view my issue.

**Comment by Vishalk91-4** [comment]
> @Vishalk91-4 could u pls help me out with this problem. while creating pull request I am getting changes in all 869 files. pls click on the following [link](https://github.com/llaske/sugarizer/issues/1378#issuecomment-1884176490) to view my issue.

Sure, I will help you out with it

**Comment by Rohan20-10** [comment]
> > @Vishalk91-4 could u pls help me out with this problem. while creating pull request I am getting changes in all 869 files. pls click on the following [link](https://github.com/llaske/sugarizer/issues/1378#issuecomment-1884176490) to view my issue.
> 
> Sure, I will help you out with it

Will u pls tell me any solution for this. It would be really very helpful.

**Comment by Vishalk91-4** [comment]
> > > @Vishalk91-4 could u pls help me out with this problem. while creating pull request I am getting changes in all 869 files. pls click on the following [link](https://github.com/llaske/sugarizer/issues/1378#issuecomment-1884176490) to view my issue.
> > 
> > 
> > Sure, I will help you out with it
> 
> Will u pls tell me any solution for this. It would be really very helpful.

Suggested the review, check it

**Comment by llaske** [comment]
Nice. Thanks @Vishalk91-4

**Pull request merged**
