### PR TITLE
Replaced bootstrap-tour by introJs in calligra activity

### PR DESCRIPTION
**Pull request by disha1202**
Fixes: #1090 
Replaced bootstrap-tour by introJs in calligra activity

[screen-recorder-tue-jan-03-2023-00-08-37.webm](https://user-images.githubusercontent.com/58461801/210268610-a5dc89a7-65a6-4a48-8560-348fca365027.webm)

### CODE REVIEW

**Comment by llaske** [comment]
Thanks @disha1202 but the help no longer work on detailed view (neither in play mode and in edit mode)

qC6hrQeum7

**Comment by disha1202** [comment]
> Thanks @disha1202 but the help no longer work on detailed view (neither in play mode and in edit mode)
> 
Fixed it. Please review again.

**Comment by llaske** [comment]
It's fixed. Thanks @disha1202 .
Could you share your experience for other contributors: why you've done this error on first PR?

**Comment by disha1202** [comment]
> Could you share your experience for other contributors: why you've done this error on first PR?
I had to update the condition for filtering steps because the element property of the step object contains the HTML element instead of a selector, and while updating the condition I forgot to add check whether the step contains an elemnt property before accessing its display property.

**Pull request merged**
