### PR TITLE
Feature/constellation activity

### PR DESCRIPTION
**Pull request by AndreaGon**
I have created a star chart for Sugarizer. Here's what it looks like:

image

I used [VirtualSky](https://virtualsky.lco.global/) to get the latest star chart.

To do list:

- [x] Add palette for projection view

- [x] Delete redundant VirtualSky files

- [x] Store type, current view and position in Journal
- [x] Add HTML5 Geolocation API?
- [x] Localize activity
- [x] Fix HTTP request?

- [x] Remove horizontal/vertical scroll bar.

### CODE REVIEW

**Comment by llaske** [comment]
Very cool idea.
Few things regarding features:
- There is scroll bar horizontally and vertically, it should not. Is it possible to reduce the canvas size to the visible zone?
- It will be nice if the current view (type, current view, position) is stored in the Journal so the user could see it where reopening it
- Why not a palette to change the projection type (like in the VirtualSky examples)?
- Where do you find the list of countries? I'm sad that France is not inside :-) Could you localize countries name and constellation names to match the current Sugarizer language?

Technically speaking:
- I guess there is something wrong: the activity continuously launch an HTTP request to get the en.json file. 
- Your PR must not integrate a ZIP file, you should unzip the content of the Constellation.activity directory. 
- Are you sure all files in the virtualsky directory are need? I'm seeing lot of redundant files and the whole activity has a size 16mb which is huge.

Thanks for this proposal.

**Comment by AndreaGon** [comment]
What I did in this PR:
1. Remove the horizontal/vertical scroll bar
2. Deleted redundant VirtualSky files and reducing the activity size to 6.13 MB
3. Added palette to change projection type.

A few matters:

1. I cannot seem to find where the activity is requesting an HTTP request. I checked using inspect element but it's not there. Can you please tell me where you found the request?

2. Regarding the list of countries: You can find them inside lib folder in the worldpalette.html. Also, I checked the list and France is in there:
image

I wouldn't forget France. I was just reading a book with French characters. :-)

**Comment by llaske** [comment]
Good. Thanks for the view and for France 🇫🇷 
Regarding horizontal/vertical scroll bar, it's still there on my side (see screen capture below). Did you try with different window size?
Regarding the HTTP request, you could see it in the browser Network tab.

capture d ecran 2019-01-29 a 16 18 31

Another thing to add in the TODO, handle offline mode. Just mean: display a small icon telling that there is no connection.

**Comment by AndreaGon** [comment]
Hi!
I'm guessing the en.json file came from the lang folder inside virtualsky folder where the translations for the star chart is placed. However, I still cannot see the HTTP request on my computer. Here is the picture of the Inspector Element in the Network tab:
request
I edited something in the virtualsky.min.js file (There is a code there that loads the en.json file, thus preventing it from changing the chart's language). I'm not sure if it fixes the HTTP request issue though.

**Comment by llaske** [comment]
Unfortunately it's don't change anything expect that it's "fr.json" is read instead of "en.json".
I've traced the call, here's the detail:

capture d ecran 2019-02-06 a 22 11 24

Look like it recursively call an error callback. 
I've tested on Chrome 71.0/Firefox 64.0.2 and Safari 12.0.2. The error doesn't happen on Safari.

**Comment by AndreaGon** [comment]
This should fix the HTTP request. I only tested it on Chrome, though, because the HTTP request is not seen on my Firefox. Let me know if the issue still persist :)

**Comment by llaske** [comment]
Same result: a continuous HTTP call to en.json file... 😞 
I've tested on another environment (Ubuntu 18.04 with Firefox 64.0), same issue.
Plus another issue on Ubuntu: [this line](https://github.com/llaske/sugarizer/pull/268/files#diff-b319ab6ac2c2a061bb8f712f86d020faR1) is wrong because `viewPalette` should be written `viewpalette` to avoid case sensitive file systems.
What's is your development environment?

**Comment by AndreaGon** [comment]
I use Atom for development, as I think, it's way faster :). As for the HTTP request, I'll try removing all the error calls in stuquery.js, there is something weird in [line 454](https://github.com/AndreaGon/sugarizer/blob/0eaf5b2ba01591e47c427b2dbfeca2b95eb25884/activities/Constellation.activity/virtualsky/stuquery.js#L454) as I tried putting a console.log(e) in it and it continously gives a TypeError, but the activity is working fine.

**Comment by llaske** [comment]
You're right it works but the continuous HTTP call is very CPU time consuming so it will be unusable on mobile device. After less than 1 minute of running the activity my own laptop fan start!
What is strange is that this not happens on the https://virtualsky.lco.global/ page so I guess that's something in your Sugarizer integration make it happens. 
Could you try to re-integrate it progressively from the initial sample to see what the problem is?

**Comment by AndreaGon** [comment]
True, it does make my Chrome and Firefox very slow. However, I noticed that the recursion calls happen inside the virtualsky.min.js file. I tried fixing that, and it works on my computer. Let me know if there are still issues, as I do not have a lot of testing environment. If there is, maybe I'll try to re-integrate it as you said :)

**Comment by llaske** [comment]
You're right it doesn't happens anymore. Good.
BTW it's a big hack, it's never a good idea to update an external library because we'll need to report your fix if we want to update the version library later.
So would be better if you try to re-integrate the library step by step to understand why it does this. It could be only a problem of directory structure.

**Comment by AndreaGon** [comment]
Hmmm, I tried creating a new experiment activity and re-integrated the star chart there step by step, but the issue still persists. However, I found out that when I use the star chart's version 0.6.7, which uses jquery instead of stuquery, it works properly. Also, [https://virtualsky.lco.global/](https://virtualsky.lco.global/) uses version 0.6.7, so I tried using it for Sugarizer.

**Comment by llaske** [comment]
Good news. Thanks to spend time to debug this.
No need to do a new PR, may be you could just replace VirtualSky version in this PR.

**Comment by AndreaGon** [comment]
@bzg Ooops, sorry, I'm new to Github. Thanks for noting :)

**Comment by bzg** [comment]
No problem, glad if I can help learning a few things!

**Comment by AndreaGon** [comment]
@llaske I've updated the css to remove the horizontal/vertical scroll bar. Let me know if it's still there :)

**Comment by llaske** [comment]
Very cool, it becomes better and better. And it's no longer send a continuous HTTP request.
I've got a new error in the console:
```

virtualsky.min.js:33 Uncaught TypeError: Cannot read property 'And' of undefined
    at VirtualSky.getPhrase (virtualsky.min.js:33)
    at VirtualSky.drawConstellationLines (virtualsky.min.js:33)
    at VirtualSky.draw (virtualsky.min.js:33)
    at VirtualSky.<anonymous> (virtualsky.min.js:33)
    at c (jquery-1.10.0.min.js:4)
    at Object.fireWith [as resolveWith] (jquery-1.10.0.min.js:4)
    at k (jquery-1.10.0.min.js:6)
    at XMLHttpRequest.r (jquery-1.10.0.min.js:6)
VirtualSky.getPhrase @ virtualsky.min.js:33
VirtualSky.drawConstellationLines @ virtualsky.min.js:33
VirtualSky.draw @ virtualsky.min.js:33
(anonymous) @ virtualsky.min.js:33
c @ jquery-1.10.0.min.js:4
fireWith @ jquery-1.10.0.min.js:4
k @ jquery-1.10.0.min.js:6
r @ jquery-1.10.0.min.js:6
XMLHttpRequest.send (async)
send @ jquery-1.10.0.min.js:6
ajax @ jquery-1.10.0.min.js:6
VirtualSky.loadJSON @ virtualsky.min.js:33
VirtualSky.load @ virtualsky.min.js:33
VirtualSky.createSky @ virtualsky.min.js:33
VirtualSky @ virtualsky.min.js:33
$.virtualsky @ virtualsky.min.js:33
(anonymous) @ activity.js:24
c @ jquery-1.10.0.min.js:4
add @ jquery-1.10.0.min.js:4
ready @ jquery-1.10.0.min.js:4
(anonymous) @ activity.js:22
execCb @ require.js:1604
check @ require.js:844
(anonymous) @ require.js:1084
(anonymous) @ require.js:129
(anonymous) @ require.js:1127
each @ require.js:57
emit @ require.js:1126
check @ require.js:898
enable @ require.js:1114
init @ require.js:757
(anonymous) @ require.js:939
(anonymous) @ require.js:129
(anonymous) @ require.js:1127
each @ require.js:57
emit @ require.js:1126
check @ require.js:898
enable @ require.js:1114
init @ require.js:757
(anonymous) @ require.js:963
(anonymous) @ require.js:129
domReady @ domReady.js:106
domReady.load @ domReady.js:122
(anonymous) @ require.js:1044
(anonymous) @ require.js:129
on @ require.js:494
callPlugin @ require.js:915
fetch @ require.js:793
check @ require.js:823
enable @ require.js:1114
(anonymous) @ require.js:956
(anonymous) @ require.js:129
(anonymous) @ require.js:1127
each @ require.js:57
emit @ require.js:1126
check @ require.js:898
enable @ require.js:1114
init @ require.js:757
callGetModule @ require.js:1141
completeLoad @ require.js:1498
onScriptLoad @ require.js:1625
load (async)
req.load @ require.js:1830
load @ require.js:1593
load @ require.js:803
fetch @ require.js:793
check @ require.js:823
enable @ require.js:1114
enable @ require.js:1465
callPlugin @ require.js:1047
fetch @ require.js:793
check @ require.js:823
enable @ require.js:1114
enable @ require.js:1465
(anonymous) @ require.js:1099
(anonymous) @ require.js:129
each @ require.js:57
enable @ require.js:1061
init @ require.js:757
(anonymous) @ require.js:1380
setTimeout (async)
req.nextTick @ require.js:1709
localRequire @ require.js:1369
requirejs @ require.js:1691
(anonymous) @ activity.js:4
execCb @ require.js:1604
check @ require.js:844
(anonymous) @ require.js:1084
(anonymous) @ require.js:129
(anonymous) @ require.js:1127
each @ require.js:57
emit @ require.js:1126
check @ require.js:898
(anonymous) @ require.js:1084
(anonymous) @ require.js:129
(anonymous) @ require.js:1127
each @ require.js:57
emit @ require.js:1126
check @ require.js:898
(anonymous) @ require.js:1084
(anonymous) @ require.js:129
(anonymous) @ require.js:1127
each @ require.js:57
emit @ require.js:1126
check @ require.js:898
enable @ require.js:1114
init @ require.js:757
callGetModule @ require.js:1141
completeLoad @ require.js:1498
onScriptLoad @ require.js:1625
load (async)
req.load @ require.js:1830
load @ require.js:1593
load @ require.js:803
fetch @ require.js:793
check @ require.js:823
enable @ require.js:1114
enable @ require.js:1465
(anonymous) @ require.js:1099
(anonymous) @ require.js:129
each @ require.js:57
enable @ require.js:1061
init @ require.js:757
callGetModule @ require.js:1141
completeLoad @ require.js:1498
onScriptLoad @ require.js:1625
load (async)
req.load @ require.js:1830
load @ require.js:1593
load @ require.js:803
fetch @ require.js:793
check @ require.js:823
enable @ require.js:1114
enable @ require.js:1465
(anonymous) @ require.js:1099
(anonymous) @ require.js:129
each @ require.js:57
enable @ require.js:1061
init @ require.js:757
callGetModule @ require.js:1141
completeLoad @ require.js:1498
onScriptLoad @ require.js:1625
load (async)
req.load @ require.js:1830
load @ require.js:1593
load @ require.js:803
fetch @ require.js:793
check @ require.js:823
enable @ require.js:1114
enable @ require.js:1465
(anonymous) @ require.js:1099
(anonymous) @ require.js:129
each @ require.js:57
enable @ require.js:1061
init @ require.js:757
callGetModule @ require.js:1141
completeLoad @ require.js:1498
onScriptLoad @ require.js:1625
load (async)
req.load @ require.js:1830
load @ require.js:1593
load @ require.js:803
fetch @ require.js:793
check @ require.js:823
enable @ require.js:1114
enable @ require.js:1465
(anonymous) @ require.js:1099
(anonymous) @ require.js:129
each @ require.js:57
enable @ require.js:1061
init @ require.js:757
callGetModule @ require.js:1141
completeLoad @ require.js:1498
onScriptLoad @ require.js:1625
load (async)
req.load @ require.js:1830
load @ require.js:1593
load @ require.js:803
fetch @ require.js:793
check @ require.js:823
enable @ require.js:1114
enable @ require.js:1465
callPlugin @ require.js:1047
fetch @ require.js:793
check @ require.js:823
enable @ require.js:1114
enable @ require.js:1465
(anonymous) @ require.js:1099
(anonymous) @ require.js:129
each @ require.js:57
enable @ require.js:1061
init @ require.js:757
callGetModule @ require.js:1141
completeLoad @ require.js:1498
onScriptLoad @ require.js:1625
load (async)
req.load @ require.js:1830
load @ require.js:1593
load @ require.js:803
fetch @ require.js:793
check @ require.js:823
enable @ require.js:1114
enable @ require.js:1465
(anonymous) @ require.js:1099
(anonymous) @ require.js:129
each @ require.js:57
enable @ require.js:1061
init @ require.js:757
callGetModule @ require.js:1141
completeLoad @ require.js:1498
onScriptLoad @ require.js:1625
load (async)
req.load @ require.js:1830
load @ require.js:1593
load @ require.js:803
fetch @ require.js:793
check @ require.js:823
enable @ require.js:1114
enable @ require.js:1465
(anonymous) @ require.js:1099
(anonymous) @ require.js:129
each @ require.js:57
enable @ require.js:1061
init @ require.js:757
callGetModule @ require.js:1141
completeLoad @ require.js:1498
onScriptLoad @ require.js:1625
load (async)
req.load @ require.js:1830
load @ require.js:1593
load @ require.js:803
fetch @ require.js:793
check @ require.js:823
enable @ require.js:1114
enable @ require.js:1465
(anonymous) @ require.js:1099
(anonymous) @ require.js:129
each @ require.js:57
enable @ require.js:1061
init @ require.js:757
(anonymous) @ require.js:1380
setTimeout (async)
req.nextTick @ require.js:1709
localRequire @ require.js:1369
requirejs @ require.js:1691
(anonymous) @ loader.js:8

```

**Comment by AndreaGon** [comment]
Hmmm, this is strange, I checked my console (both in Firefox and Chrome) and this error doesn't show. May I know what browser are you using?

**Comment by llaske** [comment]
Strange, the issue don't appear anymore. Neither on Chrome, neither on Firefox. May be it was related to an error on the VirtualSky server?

BTW can't wait to see the final version of the activity and integrate it in Sugarizer. It's a really cool activity.

**Comment by llaske** [comment]
One suggestion: could you use the user background color instead of gray for views where only a part of the screen show the sky (Ortho, Mollweide, Fisheye, ...).
It's a good practice to use colors for the user when it's possible. See background for Speak or Tam-Tam micro activities.

**Comment by AndreaGon** [comment]
I set the background color to the user color and added icon to handle offline mode in this latest commit. Let me know what you think :)

**Comment by llaske** [comment]
Very cool.

Few remarks:

- I thought the activity need Internet to run. It's not the case? If not we could completely remove the offline mode.
- Date is not localized, is it possible to localize it? For example, Clock activity use moment.js to do that.
- Will be better to use selection for "Stars" and "Constellations" buttons. So the user could see if the option is active or not (like for the current view). See Clock activity to have an example of this.
- I wonder if adding/removing one day is a good idea. May be it's better to add/remove one hour instead. Why do you think?
- Could you add compatibility with Electron? To do that you just have to put [this line](https://github.com/llaske/sugarizer/blob/dev/activities/ColorMyWorld.activity/index.html#L17) and [this line](https://github.com/llaske/sugarizer/blob/dev/activities/ColorMyWorld.activity/index.html#L19) around JavaScript libraries inclusion into your index.html file.
- When I'm running it in Electron (in full screen) the scrollbar appears again.

**Comment by AndreaGon** [comment]
Hi again! I re-read the information in the Virtualsky website and I realized that it doesn't need internet connection when the source code of the star chart from Github is used, so I completely removed the offline mode.

Regarding adding/removing one day, I added this instead of add/remove 1 hour because it can clearly show the change of position of the planets/constellations/stars. I can completely remove adding/removing one day and just set the date and time to real time, or use add/remove 1 hour instead, or probably do both?

One more note: Let me know if it know works for Electron.

**Comment by llaske** [comment]
Very cool that this activity could work fully offline.
We don't need to change behavior off add/remove buttons. Let's see feedbacks from users.
It worked on Electron, I've just fixed the scrollbar issue on it.

Finally merged the activity. It's very cool that Sugarizer could include this.
Thanks a lot for your great job on this PR. You've solved one by one each issue to obtain a perfect result. Congrats. 👏 👏 👏

**Comment by AndreaGon** [comment]
Thank you! Looking forward to contributing more for Sugar Labs 😃

**Pull request merged**
