### PR TITLE
[Fixed issue #932] Sound and Video recording of record activity in android

### PR DESCRIPTION
**Pull request by sarthak-g**
@llaske ,Fixed issue #932 for current cordova version.

RecordActivity

### CODE REVIEW

**Comment by sarthak-g** [comment]
Audio recording feature works only if there is a default audio recording app. It does not show anything for audio if there is no default recording app.
Solution:
1. Show "No recording app installed" popup if device does not contain default audio recording app.
2. Or, modify audio recording feature so that it takes directly sound from microphone instead of any app.

**Comment by llaske** [comment]
@sarthak-g is it possible to do not have an audio recording app on Android?

**Comment by sarthak-g** [comment]
@llaske 
Device with stock android generally do not have default audio recording app.

**Comment by saurabhhere** [comment]
I have created an apk using  [Sugarizer APK Builder](https://github.com/llaske/sugarizer-apkbuilder) with the image [llaske/sugarizer-apkbuilder:cordova10](https://hub.docker.com/layers/140250005/llaske/sugarizer-apkbuilder/cordova10/images/sha256-77f61cc4466de1b5d2eef76a2446c1dda99a1af2488c4d6b136a50cdab723b74?context=explore) and using https://github.com/llaske/sugarizer/tree/feature/cordova10 as `feature/codova10`  branch already have changes made in this PR.
Then I installed that apk on 3 android devices, the result of each are mentioned below:

1. First device without any audio recording app (i.e. Moto G4): Video Recording is working Fine, No Sound recording.
2. Second device is with default audio recording app (i.e OnePlus 7T ; Android Version 10): **Both Video Recording and Sound Recording not working**.
During Video Recording, the camera opens and captures the video but is not showing on the Sugarizer screen (error is shown in console). During Sound Recording, nothing happened. 

Preview of Device 2: 
Recordactivity


3. Third device is with the default audio recording app (i.e. Redmi Note 4; Android version 7): Video and Sound recording both working fine.
The camera is working fine in all three.

The outcome with device 1 and 3 are expected but I am not sure why Video and Sound recording is not working in device 2. It may be due to **Android Version 10**.
While searching for the reason, I have found this discussion on Github https://github.com/apache/cordova-plugin-media/issues/271.
Maybe this can help to fix for Android 10.

Opinions are welcome

**Comment by llaske** [comment]
Thank @sarthak-g but this fix is superseded by https://github.com/llaske/sugarizer/commit/b628ec0a24fa925b9e1081b48a3f117fdad70578 (update to Cordova 10)

**Pull request closed without merging**
