### PR TITLE
#1378 Replaced WebL10n to i18next in Paint Activity

### PR DESCRIPTION
**Pull request by Rohan20-10**
@llaske pls review this pr
Attaching ss of the results
# Replaced WebL10n to i18next in Paint Activity
IMG-20240115-WA0002

### CODE REVIEW

**Comment by llaske** [comment]
Icons tooltip are not localized. They are in the original code.

Capture d’écran du 2024-01-17 21-30-26

**Comment by Rohan20-10** [comment]
@llaske updated the updatePaint branch with required changes suggested by you in commit [5977b45](https://github.com/llaske/sugarizer/pull/1487/commits/5977b45aec2b1129a26793a835d32b2cf38edb77).
attaching ss of results
pls review this pr
image

**Comment by llaske** [comment]
> @llaske updated the updatePaint branch with required changes suggested by you in commit [5977b45](https://github.com/llaske/sugarizer/pull/1487/commits/5977b45aec2b1129a26793a835d32b2cf38edb77)

It's not the best way to handle tooltip localization. It will be better to automate the process like today. See https://github.com/llaske/sugarizer-doc/issues/42#issuecomment-1777916993

**Comment by Rohan20-10** [comment]
> > @llaske updated the updatePaint branch with required changes suggested by you in commit [5977b45](https://github.com/llaske/sugarizer/pull/1487/commits/5977b45aec2b1129a26793a835d32b2cf38edb77)
> 
> It's not the best way to handle tooltip localization. It will be better to automate the process like today. See [llaske/sugarizer-doc#42 (comment)](https://github.com/llaske/sugarizer-doc/issues/42#issuecomment-1777916993)

@llaske I am working on this and will revert to u once it is done

**Comment by llaske** [comment]
@Rohan20-10  are you still working on it?

**Comment by Rohan20-10** [comment]
@llaske yes I am working with that issue just give me a day I was busy with my clg exams.

**Comment by Rohan20-10** [comment]
@llaske  updated the updatePaint branch with the efficient way to handle tooltip localization as mentioned in the above conversation. Changes are reflected in commit [74f9efb2](https://github.com/llaske/sugarizer/pull/1487/commits/74f9efb2ed351537610320decd3f10194e553451).
attaching ss of results
pls review
Screenshot from 2024-02-04 11-34-30

**Comment by llaske** [comment]
Good job. Thanks.

**Pull request merged**
