### PR TITLE
fixed time lap

### LINKED ISSUE #638: Unnecessary display of time lapse when stopwatch not started
In stopwatch activity, unnecessary time-lapse is shown when mark button is clicked.
Screenshot from 2020-02-23 20-40-48

### PR DESCRIPTION
**Pull request by Swayamsvk**
fixed #638

### CODE REVIEW

**Comment by llaske** [comment]
Please respect indentation.

**Comment by Swayamsvk** [comment]
Fixed the indentation part, please review it.

**Comment by Swayamsvk** [comment]
I think I have made the necessary changes in the indentation please review.

**Comment by llaske** [comment]
You don't. Please indent content in the brackets.
Will be better too if the open bracket is at the end of previous line.
Try to mimic indentation style of the file.

**Comment by Swayamsvk** [comment]
Did the changes as you have suggested. Please let me know if anything else is required.

**Comment by llaske** [comment]
Nice thanks.

**Comment by llaske** [comment]
There is an issue.
Step to reproduce:
- Reopen the activity
- Click on time lap
- Click on start
- Click on time lap

A dot appear at the start of the time.

Peek 27-02-2020 21-58

**Comment by Swayamsvk** [comment]
@llaske sorry for the delay in responding. Actually I didn't get any notification about your recent comment or maybe I just have skipped it by mistake. I will fix this soon.

**Comment by quozl** [comment]
I got notification, so I think GitHub sent it.  I don't know if you are using Gmail for notifications, as your profile does not show address.  Some notifications can go missing when using Gmail.  If you are sure it is missing, check the documentation at [Gmail messages are missing](https://support.google.com/mail/answer/7015314).  This has worked for others.

**Pull request merged**
