### PR TITLE
Fixed Issue #342 (GridPaint screen don't work properly on Firefox)

### PR DESCRIPTION
**Pull request by s-mag**
Now Grid Paint Activity screen will work properly on Firefox...
gp

### CODE REVIEW

**Comment by s-mag** [comment]
@llaske Is this fine?

**Comment by llaske** [comment]
It's a good start but scrollbar should not appear when the screen is resized.

image

And of course, the idea will be to fix #403 as well because both this issues forbid Gridpaint to be responsive.

**Comment by s-mag** [comment]
Will do the changes and I will also make activity responsive...
Thanks

**Comment by s-mag** [comment]
> It's a good start but scrollbar should not appear when the screen is resized.
> 
> And of course, the idea will be to fix #403 as well because both this issues forbid Gridpaint to be responsive.

Fixed Scrollbar...
Any suggestions how to make it responsive..
Tried many things but failed..

**Comment by AndreaGon** [comment]
@s-mag Hi! You're doing great! As for responsiveness, you can try using media queries to detect when screen size is small.

**Comment by s-mag** [comment]
> @s-mag Hi! You're doing great! As for responsiveness, you can try using media queries to detect when screen size is small.

@AndreaGon I used media queries but it seems that it only resizes the border of the frame not the contents of it...

**Comment by s-mag** [comment]
The latest commit fixes issue #546.It adds a back button on top of color palette.

**Comment by s-mag** [comment]
@llaske This looks fine and enhances the UI...

**Comment by s-mag** [comment]
@llaske
Will it be fine if this PR fixes the other issues and not the responsiveness.
I will fix the responsiveness in other PR.
Can we do this???

**Comment by llaske** [comment]
Yes you can do it in another PR because it's related to another issue: #403 

BTW there is an issue in your fix, a scrollbar now appear in Chrome and the background is not the same.

Here's a capture of your fix:

image

Here's a capture before your fix:

image

**Comment by s-mag** [comment]
Oh looks like I changed the background colour. Will change that right away...

**Comment by s-mag** [comment]
@llaske Latest commit fixes background color..

**Comment by s-mag** [comment]
So this PR fixes two issues #342 & #546

**Comment by llaske** [comment]
The back icon is nice.

BTW there is now an issue in Chrome. There is a shift between the location clicked and the triangle filled.

**Comment by s-mag** [comment]
Will fix right away..

**Comment by s-mag** [comment]
@llaske Fixed the issue mentioned..

**Comment by llaske** [comment]
Hmmm. Look like there is also the same issue on Firefox now.

Peek 07-01-2020 22-35

**Comment by s-mag** [comment]
@llaske Its working fine on my side...
Can you check it again??

**Comment by s-mag** [comment]
Have a look at this...Working fine..
ezgif com-video-to-gif (2)

**Comment by s-mag** [comment]
@llaske Have a look here. Its working fine. PS. Ignore my slow computer

Chrome
ezgif com-video-to-gif (3)

Firefox
ezgif com-video-to-gif (4)

**Comment by s-mag** [comment]
@llaske Have a look here. Its working fine. PS. Ignore my slow computer

Chrome
ezgif com-video-to-gif (5)

Firefox
ezgif com-video-to-gif (4)

**Comment by s-mag** [comment]
@llaske Can you review this PR as well.The issue is not coming on my PC.

**Comment by llaske** [comment]
I've tried on another computer and I've got the issue on Firefox:

Peek 11-01-2020 16-15

Did you clear your browser cache?

**Comment by s-mag** [comment]
@llaske I got the problem..
See here if the screen size is full it works fine
ezgif com-video-to-gif (7)

But if the screen size is made small then the problem arises.
ezgif com-video-to-gif (8)

Can you suggest a way to solve this issue. I tried many things but failed to do so...

**Comment by llaske** [comment]
Everything happens in the `events.js` file and more specifically in the `localy`, `localx` methods [here](https://github.com/llaske/sugarizer/blob/dev/activities/Gridpaint.activity/js/events.js#L82).
You should have a detailed look on it and try to understand how it works and how calculation is done.

**Comment by s-mag** [comment]
@llaske Is this approach fine

**Comment by llaske** [comment]
Hmmm. I'm not in favor to add hard coded values in the source code.
In my opinion there is already too many hard coded values in the current source code of GridPaint activity! Ultimately I would love to have no (or at least less) hard coded values.
So it will be better to try to compute these values depending of the size of the screen. Specifically because the idea is later to fix https://github.com/llaske/sugarizer/issues/403 too.

Plus your current fix don't work for every window size. For example with a width of 755px or 1175px.

**Comment by s-mag** [comment]
@llaske Can I know how did you calculate these values [here](https://github.com/llaske/sugarizer/blob/dev/activities/Gridpaint.activity/js/gridpaint.js#L126) so that I can calculate value for firefox...

**Pull request closed without merging**
