### PR TITLE
Fix misalignment of close button

### LINKED ISSUE #1428: Misalignment of close button on intro dialog boxes
The close button on the intro dialog boxes in dev.sugarizer.com are bugged, whereas on server.sugarizer and try.sugarizer they are fine. 

dev bugged button

Upon comparing them on both the websites, there is an additional line-height property for the introjs-skipbutton class in the dev site, which when removed fixes the issue. This property is missing on the other sites.

Screenshot 2023-12-20 at 5 30 12 PM

### PR DESCRIPTION
**Pull request by VishnuVardhanBR**
Fixes #1428 
The button is made transparent, as suggested by @llaske

### CODE REVIEW

**Comment by llaske** [comment]
It's the first step but the style should be updated in activities styles as well. See https://github.com/llaske/sugarizer/commit/1be81b0426371c4ccf3e19206ead25d9773357b7

**Comment by llaske** [comment]
In activities the cross change color to black when the mouse is hover. Could you find an easy way to fix it?

FnWh9Oz873

**Comment by VishnuVardhanBR** [comment]
Pushed a commit, is this fine? @llaske

**Comment by llaske** [comment]
> Pushed a commit, is this fine? @llaske

Could you explain the fix?

**Comment by VishnuVardhanBR** [comment]
Any remarks on this @llaske ?

**Comment by llaske** [comment]
Good job. Thanks.

**Pull request merged**
