### PR TITLE
Fix Issue #408

### PR DESCRIPTION
**Pull request by jontymagan**
Added Icons and updated activity.js

### CODE REVIEW

**Comment by llaske** [comment]
That's a good start but you have to resize the board else no more space is available. Here you're just hiding the toolbar.

**Comment by jontymagan** [comment]
> That's a good start but you have to resize the board else no more space is available. Here you're just hiding the toolbar.

Okay.
Do I have to increase the size buttons as well because doing so results in overlapping of buttons. Moreover some buttons get hidden.

**Comment by llaske** [comment]
Adding a `sizeincrease` and `sizedecrease` function is not the good way to do that.
My idea was more to rely on current resize method in the activity called when the window size is changed. See https://github.com/llaske/sugarizer/blob/dev/activities/Calculate.activity/js/activity.js#L45

**Comment by jontymagan** [comment]
> Adding a `sizeincrease` and `sizedecrease` function is not the good way to do that.
> My idea was more to rely on current resize method in the activity called when the window size is changed. See https://github.com/llaske/sugarizer/blob/dev/activities/Calculate.activity/js/activity.js#L45

So, do I have to call just the onresize function..

**Comment by jontymagan** [comment]
When the window resizes means when the width of the window is changed the board resizes but when the length is changed their is no change.
I guess as hiding toolbar on fullscreen changes the length of the window and not the width.... the use of CalculateApp.onResize(); function is not working.

**Comment by llaske** [comment]
But there is still a margin to the size of the toolbar in fullscreen mode. This margin is a lost of space, specifically for small screens.

**Comment by llaske** [comment]
That's nice like that.
By the way the screen is not responsive so unfortunately it's not possible to see the result zone in small screens. 

image

But it's not related to the issue #408, I will fill another issue on that.

**Pull request merged**
