### PR TITLE
issue #513(fix the clean all button)

### PR DESCRIPTION
**Pull request by sarthak-g**
Clean all button is working as mentioned in issue #513 except dialog box.

### CODE REVIEW

**Comment by sarthak-g** [comment]
@llaske can you please suggest how can I approach to dialog box?

**Comment by llaske** [comment]
Nice. 

But the first page should also be reinitialized.

Peek 05-01-2020 11-29

Regarding the dialog box, may be you could use [PicoModal](https://github.com/Nycto/PicoModal) library and adapt its UI to Sugar look&feel.

**Comment by s-mag** [comment]
Hey 
To reinitialize the first page change this code:-
**toonModel._data['previews'] = [];**
                                  to
**toonModel._data['previews'] = initialData;**
This will set it to initial data.

**Comment by sarthak-g** [comment]
Correction for first page and addition of confirmation box is done.

**Comment by llaske** [comment]
That's pretty good!

image

Few remarks:
- Could you increase font size for text on buttons? (see example below)
- Could you better align text an icon in buttons? (see example below)
- Could you localize text of buttons?

image

**Comment by sarthak-g** [comment]
> Few remarks:
> 
>     * Could you increase font size for text on buttons? (see example below)
> 
>     * Could you better align text an icon in buttons? (see example below)
> 
>     * Could you localize text of buttons?
Updated code for this.

**Comment by llaske** [comment]
New localization text should be added to `localization.ini` file. See [here](https://github.com/llaske/sugarizer/blob/dev/docs/tutorial_step5.md) for more about localization.
I forgot to mention that the text of the popup should be localized too.

**Comment by sarthak-g** [comment]
Text localization done for message and buttons.

**Comment by llaske** [comment]
Good.
The "Warning" message should be localized too.

**Comment by sarthak-g** [comment]
updated localization for "Warning"

**Comment by llaske** [comment]
Good job. Thanks.

**Pull request merged**
