### PR TITLE
Replaced Bootstrap-tour by IntroJs in Dollar Street activity 

### PR DESCRIPTION
**Pull request by prakharSrivs**
#1090 
Replaced Bootstrap-tour by IntroJs in Dollar Street Activity

### CODE REVIEW

**Comment by Ayeshashaik759** [comment]
@prakharSrivs just a small suggestion from my side I think you have not made changes in css/activity.css file hope you check it once.

**Comment by prakharSrivs** [comment]
Thank you for reviewing it @Ayeshashaik759 
I'll be shortly pushing an update to the branch

**Comment by Ayeshashaik759** [comment]
> Thank you for reviewing it @Ayeshashaik759 I'll be shortly pushing an update to the branch

No mention 😊

**Comment by llaske** [comment]
The Things popup is missing in the detailed view tutorial.

image

**Comment by llaske** [comment]
@prakharSrivs are you still working on it?

**Comment by prakharSrivs** [comment]
Hi @llaske , Actually my midterms were going on so I was not able to work on it.
But I will surely look into it now.

**Comment by llaske** [comment]
Fixed by https://github.com/llaske/sugarizer/pull/1242

**Pull request closed without merging**
