### PR TITLE
QR Code : Image Activity Loading Spinner 

### LINKED ISSUE #1268: QR activity Photo Loading Icon Overlaping
Hey @llaske 

the Image loading icon , and Drop Down  icon is overlapping Each other in the Photo Activity of QR activity

image

We can fix it ,by keeping it next to the drop down icon
like this 
image

Please share your thought on this.

### PR DESCRIPTION
**Pull request by kanishkcs**
Fixes #1268

### CODE REVIEW

**Comment by llaske** [comment]
Sound like it depend of the resolution.

image

**Comment by kanishkcs** [comment]
Hey @llaske  , i have  made the neccessary changes kindly Review it

**Comment by llaske** [comment]
Same issue here.

image

**Comment by llaske** [comment]
@kanishkcs are you still working on it?

**Comment by kanishkcs** [comment]
yes @llaske  , i was ill, so wasnt onlinee for days, now i am back, and will realease the fix, by today, sorry for the delay

**Comment by samyakshah3008** [comment]
Hey @llaske , shall we consider to close this PR because Vishal's PR #1394 has fixed this issue.

**Comment by llaske** [comment]
You're right @samyakshah3008.

**Pull request closed without merging**
