### PR TITLE
Placeholder in search bar is now readable

### PR DESCRIPTION
**Pull request by abhishektiwari47**
Previously the the placeholder "Search in Neighborhood" was becoming unreadable in smaller screens.
Hence some changes were needed to fix this issues. Now the whole placeholder is visible without making any disturbance with rest of the UI

### CODE REVIEW

**Comment by abhishektiwari47** [comment]
This might not be visible on a wider screen but you will find this problem in small screen. Just reduce the screen size to half.

**Comment by llaske** [comment]
Do not send PR without an issue. We need to reproduce your issue before validating your PR.
Specifically it's not clear here what the issue is. What means unreadable ? Which screen size?

**Comment by abhishektiwari47** [comment]
Thanks for this guidance. I will mention the issue soon.

**Comment by abhishektiwari47** [comment]
Sir, can you please tell me the name of GSOC 23 mentors. Are you one of
them?

**Comment by llaske** [comment]
Yes I am. The GSoC 2023 mentors list is available on https://github.com/sugarlabs/GSoC/blob/master/Ideas-2023.md

**Pull request closed without merging**
