### PR TITLE
Migrating memorize activity to intro js

### PR DESCRIPTION
**Pull request by jain-arihant-2002**
Last tooltip not showing....

### CODE REVIEW

**Comment by jain-arihant-2002** [comment]
Last tool tip is not showing but can't find problem with code. Review(s) and comment(s) are appreciated.

**Comment by jain-arihant-2002** [comment]
image

**Comment by Ayeshashaik759** [comment]
hlo @jain-arihant-2002 you have to remove the lines 50, 51, 52 of code in tutorial.js hope this helps you.
Screenshot from 2023-01-30 09-54-38

**Comment by jain-arihant-2002** [comment]
@Ayeshashaik759 what you mean by first tooltip?

**Comment by jain-arihant-2002** [comment]
@llaske Can you check my pr and merge it or give feedback.

**Comment by Ayeshashaik759** [comment]
@jain-arihant-2002 also make the changes in activity.css

**Comment by llaske** [comment]
For maintainability reason, you should update only files/lines that need to be changed.
Please update only what's needed.
I guess your IDE have done auto formatting on each updated file.

**Comment by jain-arihant-2002** [comment]
@llaske Only files that need to be changed are changed in the commits and I will keep in mind that my IDE don't format whole code in future. For now is this code ok or you need me to make some changes?

**Comment by llaske** [comment]
> Only files that need to be changed are changed in the commits 

No. 
See for example following lines where you've updated Space/TAB/New line without any reason:

image

image

image

Yes, I'm expecting that you fix the issue.

**Comment by Ayeshashaik759** [comment]
@jain-arihant-2002 I can suggest you that it's better to redo the whole process again as many lines are auto formatted by the code editor mostly it will be very difficult for you to format space for every line changed

**Comment by jain-arihant-2002** [comment]
Ok

**Comment by jain-arihant-2002** [comment]
Closing this pr as new pr is made with proper changes suggested above.

**Pull request closed without merging**
