### PR TITLE
Replaced Bootstrap tour by IntroJs in TamTam Micro Activity

### PR DESCRIPTION
**Pull request by ABHINAV-JHA-27**
Migrated TamTam Micro Activity from Bootstrap Tour to IntroJs https://github.com/llaske/sugarizer/issues/1090

### CODE REVIEW

**Comment by ABHINAV-JHA-27** [comment]
Hey @llaske , Can you have a look.

**Comment by llaske** [comment]
Your PR include both TamTam micro and Reflection update.
The Reflection part doesn't concern this fix.

**Comment by ABHINAV-JHA-27** [comment]
Hi @llaske , Sorry for the mistake, I have ensured that only changes related to the TamTam micro activity is only present now.
Can you review it?

**Comment by llaske** [comment]
@ABHINAV-JHA-27 Do not change indentation, only updated lines should be change in your PR.

**Comment by ABHINAV-JHA-27** [comment]
hey @llaske , fixed the formatting issue , can you review it.

**Comment by llaske** [comment]
@ABHINAV-JHA-27 the problem is still there in index.html

**Pull request closed without merging**
