### PR TITLE
CHESS ACTIVITY : GSoC 2020 CHALLENGE

### PR DESCRIPTION
**Pull request by abhishektanwar**
Solves #592 

- Full Screen functionality added.
- Tutorial Added.
- Game Logs visible.
chess_Offline

- Multiplayer added.
chess_online

### CODE REVIEW

**Comment by llaske** [comment]
Nice. But it's just a beginning.

My remarks:

* The icon for activity should be changed: why not a king pawn
* Lot of features are not "Sugarized" (your footer text) and should be integrated in the toolbar
* When the window is resize the tutorial don't select correctly pawns
* There is permanent scrollbar over the window
* You should switch position of fullscreen icon and help icon

**Comment by abhishektanwar** [comment]
@llaske I have made the requested changes.
- added game restart functionality from toolbar
- background color changes according to buddy color
- removed footer and added to toolbar
- resizing fixed
- permanent scrollbar removed
- position of fullscreen and help icon fixed

**Comment by abhishektanwar** [comment]
@ashish0910 @llaske could you please review the changes?

**Comment by ashish0910** [comment]
Few remarks :

- On starting the game the screen overflows 
- Possible moves should be highlighted on selecting the character ( Also I would prefer drag and drop rather than current implementation ) .
- White colour SVG icon for restart and swap should be used

Screenshot 2020-03-13 at 6 43 39 PM

**Comment by abhishektanwar** [comment]
@ashish0910 @llaske please review
-fixed sizing 
-fixed icons 
-working on move highlight

**Comment by ashish0910** [comment]
Few Remarks : 

- Possible moves of selected character should be highlighted 
- Drag and drop feature will be preferred rather than current implementation

**Comment by llaske** [comment]
Thanks for your proposal but it's too basic.

**Pull request closed without merging**
