### PR TITLE
Message for MediaViewer activity empty

### PR DESCRIPTION
**Pull request by S-kus**
Fixes: #1003 

The message appearance is fixed without any error in the console, but the message is still not localized properly, it's kind of getting overwritten. As shown:

https://user-images.githubusercontent.com/86892991/171504463-51d1bb28-6b34-4d02-9861-3f1d6d84fac5.mp4

@llaske could you please guide me on the localization part.
Thank you!

### CODE REVIEW

**Comment by llaske** [comment]
This [line](https://github.com/llaske/sugarizer/blob/dev/activities/MediaViewer.activity/js/activity.js#L7) prevent your localization code to be executed. The test is the same that `if (!environment.objectId)` in the tutorial.

You should put your code before and it should work.

**Comment by llaske** [comment]
Okay nice.

Just two things:
- For the message I suggest "You need to open an existing media from the Journal" (without dot at end)
- Use the English message for all translation. It's better to let translation to native speakers instead of using Google translate.

**Comment by llaske** [comment]
Also, the message is not responsive. It should be in the middle of the screen whatever the size is.

Peek 03-06-2022 21-58

**Comment by S-kus** [comment]
Sure @llaske, I have corrected these changes in the recent commit.

**Comment by llaske** [comment]
Nice. Thanks.
On localization you should create strings for common languages (en, fr, es, de) but use the English value for all. So translators will know they have work to do.

**Comment by S-kus** [comment]
> Nice. Thanks. On localization you should create strings for common languages (en, fr, es, de) but use the English value for all. So translators will know they have work to do.

It's merged now! Should I still commit with suggested changes?

**Comment by llaske** [comment]
> This pull request merged now! Should I still commit with suggested changes?

No that's fine. I've done it.
Just remember that for next time.

**Comment by S-kus** [comment]
Okay Thanks @llaske, I will be careful about this next time.

**Pull request merged**
