### PR TITLE
Improve calculator screen responsivity 

### PR DESCRIPTION
**Pull request by codebloded**
The issue #982  is resolved @llaske  have a look on the screenshots, and you can give suggestion to do the changes in this screen 

screenshots  in different mobile screens :arrow_down: 

Screenshot from 2022-02-28 20-26-20
Screenshot from 2022-02-28 20-25-55

### CODE REVIEW

**Comment by llaske** [comment]
Sugarizer is not responsive in every case. Specifically the Window width should be greater than Window height. Read [this](https://github.com/llaske/sugarizer/issues/422) for more.
BTW you're right, there is room for improvement.

**Comment by llaske** [comment]
Thanks for this PR. Sounds good.
BTW PR should be send on dev branch, see [here](https://github.com/llaske/sugarizer/blob/dev/CONTRIBUTING.md) for more.

**Comment by codebloded** [comment]
okay @llaske  i'll shift the changes to the dev branch , Thank you

**Comment by llaske** [comment]
Fixed in https://github.com/llaske/sugarizer/commit/0cd094b944cce8d2154cee7807e3ad281d82b52e

**Pull request closed without merging**
