### PR TITLE
Fix: Activity Description opening downwards in Journal #1407

### PR DESCRIPTION
**Pull request by AdityaKrSingh26**
For the last icon the popup appears up instead of downwards . Popup remains on the same page instead of extending page downwards. (issue : #1407)
image

### CODE REVIEW

**Comment by llaske** [comment]
Nice. But it only fix partially the problem in the Journal: the popup is still under the footer.

[capture.webm](https://github.com/user-attachments/assets/a41f0a92-2b03-474a-9f96-6bb4c71b2ec4)

**Comment by AdityaKrSingh26** [comment]
okay, i will fix this

**Comment by AdityaKrSingh26** [comment]
@llaske i have opened a new pr to the issue i have fixed the issue you mentioned could you please review it 

https://github.com/user-attachments/assets/9e9f2e56-83b5-4279-a7e4-f19e53b96a1f

**Comment by llaske** [comment]
The issue I've mentioned is in the Journal view not in the listview.
Your new fix doesn't change anything.

**Comment by AdityaKrSingh26** [comment]
Hey @llaske please have a look at my latest commit.

[Screencast from 2024-12-10 00-12-34.webm](https://github.com/user-attachments/assets/a742ecf8-0365-47f2-842f-c88a3cc91958)

**Comment by AdityaKrSingh26** [comment]
In my latest commit i have made sure that the popup remains on the same page preventing it form increasing the page length.

**Comment by llaske** [comment]
Good. But the footer is not always here (when the user is not connected).
In this case there's a gap.

[Capture vidéo du 2024-12-11 22-19-11.webm](https://github.com/user-attachments/assets/3fbd9549-c4bf-41ee-a6df-cdb6b61978e6)

**Comment by AdityaKrSingh26** [comment]
> Good. But the footer is not always here (when the user is not connected). In this case there's a gap.
> 
>  Capture.video.du.2024-12-11.22-19-11.webm

Okay ... i will work upon this

**Comment by AdityaKrSingh26** [comment]
> Good. But the footer is not always here (when the user is not connected). In this case there's a gap.
> 
>  Capture.video.du.2024-12-11.22-19-11.webm

Please have a look at my latest commit

**Comment by llaske** [comment]
Nice. Thanks.

**Pull request merged**
